### ISSUE TITLE
ERROR: unknown command line flag 'caffe2_gpu_memory_tracking'

### ISSUE THREAD

**Issue by josepqp** [facebookresearch/Detectron#127]
I followed all installation instructions and I was able to test:

python2 tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo

and

python2 tools/test_net.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    TEST.WEIGHTS https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    NUM_GPUS 1

but when I tried to run "Training a Model with Detectron":

python2 tools/train_net.py \
    --cfg configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml \
    OUTPUT_DIR /tmp/detectron-output

I got this output:

ERROR: unknown command line flag 'caffe2_gpu_memory_tracking'

any suggestion ?

**Comment by ir413** [comment]
@josepqp: I'm unable to reproduce this issue neither with the latest Caffe2 master nor with a few older Caffe2 versions. I expect that the `unknown command line flag 'caffe2_gpu_memory_tracking'` error could occur when using Caffe2 without GPU support. Though, given that you're able to run inference, that seems unlikely.

**Comment by josepqp** [comment]
If I change line 98 at tools/train_net.py:

['caffe2', '--caffe2_log_level=0']

to

['caffe2', '--caffe2_log_level=0'] #, '--caffe2_gpu_memory_tracking=1']

works for a while, but I'm not sure about what "caffe2_gpu_memory_tracking" flag does.

but I finally obtain this error:

INFO net.py: 244: End of model: generalized_rcnn
Traceback (most recent call last):
  File "tools/train_net.py", line 281, in <module>
    main()
  File "tools/train_net.py", line 119, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 145, in train_model
    training_stats.LogIterStats(cur_iter, lr)
  File "/home/josep2/detectron/lib/utils/training_stats.py", line 88, in LogIterStats
    stats = self.GetStats(cur_iter, lr)
  File "/home/josep2/detectron/lib/utils/training_stats.py", line 96, in GetStats
    mem_stats = c2_py_utils.GetGPUMemoryUsageStats()
  File "/home/josep2/caffe2/build/caffe2/python/utils.py", line 234, in GetGPUMemoryUsageStats
    device_option=core.DeviceOption(caffe2_pb2.CUDA, 0),
  File "/home/josep2/caffe2/build/caffe2/python/workspace.py", line 176, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
SystemError: error return without exception set

**Comment by josepqp** [comment]
@ir413 if I run:

python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'

the output is:

2

then I have support for GPU
