### ISSUE TITLE
Help in converting pkl to pb file

### ISSUE THREAD

**Issue by vvrmahendra** [facebookresearch/Detectron#134]
I tried to convert mask r-cnn pkl file to caffe2 pb file with the ``convert_pkl_to_pb.py`` script. I am confused what to pass in for --cfg option. There are several yaml files that are in ``config`` directory, but it looks like these are for train, test etc. The documentation in the ``convert_pkl_to_pb.py`` says to copy / create a new yaml based of ``lib/core/config.py`` but I am not sure what options would go in this yaml file. Is there a sample yaml config file available?

### Expected results

What did you expect to see?

### Actual results

What did you observe instead?

### Detailed steps to reproduce

E.g.:

```
The command that you ran
```

### System information

* Operating system: ?
* Compiler version: ?
* CUDA version: ?
* cuDNN version: ?
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by alllegrodeveloper** [comment]
you should take a look at this :https://github.com/facebookresearch/Detectron/blob/master/tools/convert_pkl_to_pb.py

**Comment by bendidi** [comment]
in [here](https://github.com/facebookresearch/Detectron/blob/master/tools/convert_pkl_to_pb.py#L525) it says that FPN is not supported , so actually most models can't be converted , or is there a hack I don't know of ?

**Comment by bendidi** [comment]
Actually `assert not cfg.FPN.FPN_ON, "FPN not supported."` means exactly the opposite of what you said :) 

my first try was with FPN_on set on True
```
'FPN': {'COARSEST_STRIDE': 32,
         'DIM': 256,
         'EXTRA_CONV_LEVELS': False,
         'FPN_ON': True,
         'MULTILEVEL_ROIS': True,
         'MULTILEVEL_RPN': True,
         'ROI_CANONICAL_LEVEL': 4,
         'ROI_CANONICAL_SCALE': 224,
         'ROI_MAX_LEVEL': 5,
         'ROI_MIN_LEVEL': 2,
         'RPN_ANCHOR_START_SIZE': 32,
         'RPN_ASPECT_RATIOS': (0.5, 1, 2),
         'RPN_MAX_LEVEL': 6,
         'RPN_MIN_LEVEL': 2,
         'ZERO_INIT_LATERAL': False},
```
and I still get the assertion error : 

```
Traceback (most recent call last):
  File "tools/convert_pkl_to_pb.py", line 571, in <module>
    main()
  File "tools/convert_pkl_to_pb.py", line 525, in main
    assert not cfg.FPN.FPN_ON, "FPN not supported."
AssertionError: FPN not supported.
```

**Comment by blateyang** [comment]
Sorry, I misunderstood the code. You are right.@bendidi Hope someone else can explain it.

**Comment by orionr** [comment]
We are working on FPN support (the `CollectAndDistributeFpnRpnProposals` operator) with standard Caffe2 C++, so stay tuned.

**Comment by ChengshuLi** [comment]
@orionr 

Do you have a rough estimation of the timeline about this FPN support with standard Caffe2 c++? Thanks a ton!

**Comment by Luyang1125** [comment]
I'm also interested in transfer the pkl file to pb. Want to know what is the current status on this. Thanks!

**Comment by gadcam** [comment]
If #372  is merged it should close this issue.

**Comment by Gautam1121** [comment]
I am facing issue in getting mask, lost mask in the conversion.
I have used " Detectron/tools/convert_pkl_to_pb.py " file to convert my model.

How can i get mask as well?

Help appreciated, thanks :)

**Comment by ashuGulati** [comment]
how to convert a .pb to .pkl format?
