### ISSUE TITLE
Error during test_spatial_narrow_as_op.py while installing

### ISSUE THREAD

**Issue by PardoAlejo** [facebookresearch/Detectron#139]
### System information

* Operating system: Ubuntu 16.04.3 LTS
* Compiler version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
* CUDA version: CUDA 8.0
* cuDNN version: cuDNN 6.0
* NVIDIA driver version: nvidia-387
* GPU models (for all devices if they are not all the same): Titan X
* `PYTHONPATH` environment variable: /usr/local/lib/python2.7
* `python --version` output: Python 2.7.12

Hi,

I've been trying to install detectron in my machine. After following all steps required in install.md I check te installation by running python2 $DETECTRON/tests/test_spatial_narrow_as_op.py. And I get the following error:

ERROR: test_large_forward (__main__.SpatialNarrowAsOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_spatial_narrow_as_op.py", line 68, in test_large_forward
    self._run_test(A, B)
  File "test_spatial_narrow_as_op.py", line 37, in _run_test
    workspace.FeedBlob('A', A)
  File "/usr/local/caffe2/python/workspace.py", line 322, in FeedBlob
    return C.feed_blob(name, arr, StringifyProto(device_option))
RuntimeError: [enforce fail at common_cudnn.h:118] version_match. cuDNN compiled (7005) and runtime (7003) versions mismatch 

Could anyone help me to figure out what is wrong with the installation?

**Comment by ir413** [comment]
Hi @PardoAlejo, it seems that your cuDNN versions are getting mixed. Please ensure that the same cuDNN version is used to compile Caffe2 and at runtime.

You may want to check that your `$LD_LIBRARY_PATH` does not point to a cuDNN version different from the one used to compile Caffe2 (if it does, try removing it).

**Comment by EP777** [comment]
Look for the compiled version, for 7005, use - Download cuDNN v7.0.5 (Dec 5, 2017), for CUDA 9.0 version

**Comment by ambigus9** [comment]
Hi, I install Caffe2 from Anaconda Pre-build Binaries with CUDA 8.0  and cuDNN 7.1.2 and got this error:

 `RuntimeError: [enforce fail at common_cudnn.h:118] version_match. cuDNN compiled (7101) and runtime (7102) versions mismatch `

How can I "uninstall" or use the same version? I tried 

sudo dpkg -i libcudnn7_7.1.1.5-1+cuda8.0_amd64.deb
sudo dpkg -i libcudnn7-dev_7.1.1.5-1+cuda8.0_amd64.deb

and also,

```
tar -xzvf cudnn-8.0-linux-x64-v7.1.tgz

sudo cp cuda/include/cudnn.h /usr/local/cuda/include
sudo cp cuda/lib64/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*
```

But doesn't work

**Comment by lupotto** [comment]
Hi, 

I am having the exact problem as @ambigus9.

**Comment by jhonygiraldo** [comment]
Hi,

I have the exact problem as @ambigus9 too.

**Comment by ambigus9** [comment]
@lupotto and @jhonygiraldo Please download the tar file wich this version cuDNN v7.1.1 Library for Linux from [](https://developer.nvidia.com/rdp/cudnn-download) using **wget** (click on the file to download it, and copy the download link an use wget) because for somereason download it from a browser doesn't download well, and make this steps:

```
tar -xzvf cudnn-8.0-linux-x64-v7.1.tgz

sudo cp cuda/include/cudnn.h /usr/local/cuda/include
sudo cp cuda/lib64/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*
```
After this you should check your version of cuDNN,
`cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2`

Hope to help.

**Note:** It's better to build a Docker image using Dockerfile.

**Comment by lupotto** [comment]
Hi @ambigus9,

Thank you for sharing this. But I still stuck in the same problem, I will try with Docker.

**Comment by IgorKasianenko** [comment]
Hi, I'm having similar issue. I'm using env to run another framework.
I don't use conda or docker to install caffe2 and Detectron.
Error as follows `version_match. cuDNN compiled (7102) and runtime (7005) versions mismatch`

What is better solution - recompile caffe2 and Detectron with version 7005 that i need for another project or create virual env like conda for Detectron and use latest version of cuDNN?

**Comment by jhonygiraldo** [comment]
Hi @IgorKasianenko,

I think that the error message is a little bit confusing. You should uninstall caffe2, then install **cuDNN v7.1.2 (Mar 21, 2018), for CUDA 9.0** or **cuDNN v7.1.2 (Mar 21, 2018), for CUDA 9.1** (see your CUDA version). Finally, install again Caffe2.

**Comment by xingkongliang** [comment]
I find a cuDNN v7.1.2 in my an conda, so I uninstall this cudnn
`conda uninstall cudnn`
after that, I rebuid caffe2, I pass it.

**Comment by mbajaj01** [comment]
Facing same issue. Any solution for this without using docker?
