### ISSUE TITLE
train_net.py failed when saving parameters and momentum

### ISSUE THREAD

**Issue by MrMYHuang** [facebookresearch/Detectron#163]
### Expected results

Output (models, validation set detections, etc.) will be saved under *out2*.

### Actual results

Saving failed.

### Detailed steps to reproduce

The command ([See "Training a Model with Detectron/Training with 1 GPU"](https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md)) that I ran:
```
python2 tools/train_net.py --cfg configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml OUTPUT_DIR out2
```
After about 1 hour, I got the error messages:
```
...
json_stats: {"accuracy_cls": 0.871094, "eta": "2:38:01", "iter": 19960, "loss": 0.819866, "loss_bbox": 0.220778, "loss_cls": 0.363075, "loss_rpn_bbox_fpn2": 0.013044, "loss_rpn_bbox_fpn3": 0.003122, "loss_rpn_bbox_fpn4": 0.001757, "loss_rpn_bbox_fpn5": 0.016337, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.056191, "loss_rpn_cls_fpn3": 0.016754, "loss_rpn_cls_fpn4": 0.006615, "loss_rpn_cls_fpn5": 0.002712, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 64, "mem": 3300, "time": 0.236790}
json_stats: {"accuracy_cls": 0.886719, "eta": "2:37:56", "iter": 19980, "loss": 0.767911, "loss_bbox": 0.208941, "loss_cls": 0.381464, "loss_rpn_bbox_fpn2": 0.002767, "loss_rpn_bbox_fpn3": 0.001394, "loss_rpn_bbox_fpn4": 0.007436, "loss_rpn_bbox_fpn5": 0.025394, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.025190, "loss_rpn_cls_fpn3": 0.018177, "loss_rpn_cls_fpn4": 0.011314, "loss_rpn_cls_fpn5": 0.002561, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 64, "mem": 3300, "time": 0.236784}
INFO net.py: 140: Saving parameters and momentum to /home2/grad97/myh/git/detectron/out2/train/coco_2014_train/generalized_rcnn/model_iter19999.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 281, in <module>
    main()
  File "tools/train_net.py", line 119, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 151, in train_model
    nu.save_model_to_weights_file(checkpoints[cur_iter], model)
  File "/home2/grad97/myh/git/detectron/lib/utils/net.py", line 165, in save_model_to_weights_file
    cfg_yaml = yaml.dump(cfg)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 61, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 447, in represent_object
    return self.represent_mapping(tag+function_name, value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 41, in represent_data
    if self.ignore_aliases(data):
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 142, in ignore_aliases
    if data in [None, ()]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
### System information

* Operating system: CentOS 7.4.1708
* Compiler version: gcc version 4.8.5
* CUDA version: 9.0
* cuDNN version: 7.0.5
* NVIDIA driver version: 384.81
* GPU models (for all devices if they are not all the same): GeForce GTX 1070
* `PYTHONPATH` environment variable: /usr
* `python --version` output: Python 2.7.5
* Detectron commit: 021685d42f7e8ac097e2bcf79fecb645f211378e
* caffe2 commit: 17fbf997f226996b78660b0651df93f17d13efb9

**Comment by ir413** [comment]
Hi @MrMYHuang, this may be the same as #23. Please make sure you're using the recommended versions of numpy (1.13) and yaml (3.12).

**Comment by MrMYHuang** [comment]
@ir413 , Thank you. I upgrade PyYAML from 3.10 to 3.12. It fixes the problem.
