### ISSUE TITLE
save model.pkl error

### ISSUE THREAD

**Issue by oujieww** [facebookresearch/Detectron#194]
I use 5000iter.but
INFO net.py: 140: Saving parameters and momentum to /mnt/disk1/oujie/Detectron-master/lib/out_put/train/keypoints_coco_2014_train:keypoints_coco_2014_valminusminival:coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl
Traceback (most recent call last):
  File "../tools/train_net.py", line 291, in <module>
    main()
  File "../tools/train_net.py", line 129, in main
    checkpoints = train_model()
  File "../tools/train_net.py", line 175, in train_model
    nu.save_model_to_weights_file(checkpoints['final'], model)
  File "/mnt/disk1/oujie/Detectron-master/lib/utils/net.py", line 165, in save_model_to_weights_file
    cfg_yaml = yaml.dump(cfg)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 61, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 447, in represent_object
    return self.represent_mapping(tag+function_name, value)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 41, in represent_data
    if self.ignore_aliases(data):
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 142, in ignore_aliases
    if data in [None, ()]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

can anyone help me ? please

**Comment by uefall** [comment]
you may check your pyyaml version if it is 3.12

**Comment by oujieww** [comment]
@uefall thank you!!!this work for me !!! thanks!!!
