### ISSUE TITLE
Turn off horizontal flipped, and ValueError generated: cannot reshape array

### ISSUE THREAD

**Issue by whale9067** [facebookresearch/Detectron#208]
### Expected results

I'm training my custom dataset. In my annotation, left hand and right hand are 2 different classes, so I will need to disable horizontal flipping.
When I add `USE_FLIPPED: False` in .yaml file, error generated:

```
python2 tools/train_net.py \
--cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
TRAIN.USE_FLIPPED False \
OUTPUT_DIR /l/vision/v3/cw234/train_MASK_R101FPN_2x_non-flipped
```

```
......
loading annotations into memory...
Done (t=1.04s)
creating index...
index created!
INFO roidb.py:  51: Loaded dataset: ego_data_train
INFO roidb.py: 135: Filtered 13 roidb entries: 3600 -> 3587
INFO roidb.py:  67: Computing bounding-box regression targets...
INFO roidb.py:  69: done
INFO train_net.py: 257: 3587 roidb entries
Traceback (most recent call last):
  File "tools/train_net.py", line 281, in <module>
    main()
  File "tools/train_net.py", line 119, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 133, in train_model
    setup_model_for_training(model, output_dir)
  File "tools/train_net.py", line 231, in setup_model_for_training
    add_model_training_inputs(model)
  File "tools/train_net.py", line 258, in add_model_training_inputs
    model_builder.add_training_inputs(model, roidb=roidb)
  File "/nfs/zapdos/home/data/vision3/cw234/detectron/lib/modeling/model_builder.py", line 385, in add_training_inputs
    roidb, num_loaders=cfg.DATA_LOADER.NUM_THREADS
  File "/nfs/zapdos/home/data/vision3/cw234/detectron/lib/roi_data/loader.py", line 94, in __init__
    self._shuffle_roidb_inds()
  File "/nfs/zapdos/home/data/vision3/cw234/detectron/lib/roi_data/loader.py", line 152, in _shuffle_roidb_inds
    inds = np.reshape(inds, (-1, 2))
  File "/u/cw234/anaconda2/envs/my_caffe2_env/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/u/cw234/anaconda2/envs/my_caffe2_env/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 3587 into shape (2)
```

Anyone know how to solve it? Thanks!!

### System information

* Operating system: Linux Server release 7.4 (Maipo)
* Compiler version: gcc/5.2.0
* CUDA version: 8.0
* cuDNN version: 7.0.5
* NVIDIA driver version: 390.30
* GPU models (for all devices if they are not all the same): TITAN X (Pascal)
* PYTHONPATH environment variable: /l/vision/v3/cw234/caffe2/build
* python --version output: Python 2.7.14

**Comment by kampelmuehler** [comment]
This happens because the shuffling of the roidb
```
File "detectron/lib/roi_data/loader.py", line 152, in _shuffle_roidb_inds
    inds = np.reshape(inds, (-1, 2))
```
fails when the number of samples in the roidb is uneven. You can quickfix this by removing one element from the roidb to make it even length. This is still from the py fast rcnn implementation.

**Comment by whale9067** [comment]
@kampelmuehler Thanks! It worked. It seems some of my data got filter because they don't have fore/background RoI detected. It doesn't help even I changed the FG/BG_THRES. I'm looking into the code to figure out why, but thanks a lot!!!
