### ISSUE TITLE
Changing loss function of the mask_rcnn_head causing gradient not found

### ISSUE THREAD

**Issue by quadroctor** [facebookresearch/Detectron#215]
When I don't have the change, I was able to train the model with Mask ON and the results seems correct, so all the path and env should've been set up correctly. Please help take a look at following issue and thanks in advance!

### Expected results

After modifying the loss function for mask rcnn head, the forward and backward model get build without errors

### Actual results

An error raised when trying to AddGradientOperators to the model:
Traceback (most recent call last):
  File "tools/train_net.py", line 281, in <module>
    main()
  File "tools/train_net.py", line 119, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 128, in train_model
    model, start_iter, checkpoints, output_dir = create_model()
  File "tools/train_net.py", line 206, in create_model
    model = model_builder.create(cfg.MODEL.TYPE, train=True)
  File "/home/tianxi/disk2/detectron/lib/modeling/model_builder.py", line 127, in create
    return get_func(model_type_func)(model)
  File "/home/tianxi/disk2/detectron/lib/modeling/model_builder.py", line 92, in generalized_rcnn
    freeze_conv_body=cfg.TRAIN.FREEZE_CONV_BODY
  File "/home/tianxi/disk2/detectron/lib/modeling/model_builder.py", line 246, in build_generic_detection_model
    optim.build_data_parallel_model(model, _single_gpu_build_func)
  File "/home/tianxi/disk2/detectron/lib/modeling/optimizer.py", line 40, in build_data_parallel_model
    all_loss_gradients = _build_forward_graph(model, single_gpu_build_func)
  File "/home/tianxi/disk2/detectron/lib/modeling/optimizer.py", line 64, in _build_forward_graph
    all_loss_gradients.update(single_gpu_build_func(model))
  File "/home/tianxi/disk2/detectron/lib/modeling/model_builder.py", line 219, in _single_gpu_build_func
    spatial_scale_conv
  File "/home/tianxi/disk2/detectron/lib/modeling/model_builder.py", line 308, in _add_roi_mask_head
    loss_gradients = mask_rcnn_heads.add_mask_rcnn_losses(model, blob_mask)
  File "/home/tianxi/disk2/detectron/lib/modeling/mask_rcnn_heads.py", line 112, in add_mask_rcnn_losses
    model.AddGradientOperators([loss_depth])
  File "/home/tianxi/disk2/caffe2/caffe2/build/caffe2/python/model_helper.py", line 350, in AddGradientOperators
    self.grad_map = self.net.AddGradientOperators(*args, **kwargs)
  File "/home/tianxi/disk2/caffe2/caffe2/build/caffe2/python/core.py", line 1842, in AddGradientOperators
    self._net.op[skip:], ys)
  File "/home/tianxi/disk2/caffe2/caffe2/build/caffe2/python/core.py", line 1109, in GetBackwardPass
    return ir.GetBackwardPass(ys)
  File "/home/tianxi/disk2/caffe2/caffe2/build/caffe2/python/core.py", line 984, in GetBackwardPass
    forward_op_idx, all_input_to_grad)
  File "/home/tianxi/disk2/caffe2/caffe2/build/caffe2/python/core.py", line 934, in _GenerateGradientsForForwardOp
    forward_op, g_output)
  File "/home/tianxi/disk2/caffe2/caffe2/build/caffe2/python/core.py", line 1082, in GetGradientForOp
    format(op.type, e, str(op))
Exception: Exception when creating gradient for [Python]:[enforce fail at operator_gradient.h:166] g_output_.at(i).IsDense(). Gradient of output gpu_0/rois is not provided! .
Op: 
input: "gpu_0/rpn_rois_fpn2"
input: "gpu_0/rpn_rois_fpn3"
input: "gpu_0/rpn_rois_fpn4"
input: "gpu_0/rpn_rois_fpn5"
input: "gpu_0/rpn_rois_fpn6"
input: "gpu_0/rpn_roi_probs_fpn2"
input: "gpu_0/rpn_roi_probs_fpn3"
input: "gpu_0/rpn_roi_probs_fpn4"
input: "gpu_0/rpn_roi_probs_fpn5"
input: "gpu_0/rpn_roi_probs_fpn6"
input: "gpu_0/roidb"
input: "gpu_0/im_info"
output: "gpu_0/rois"
output: "gpu_0/labels_int32"
output: "gpu_0/bbox_targets"
output: "gpu_0/bbox_inside_weights"
output: "gpu_0/bbox_outside_weights"
output: "gpu_0/mask_rois"
output: "gpu_0/roi_has_mask_int32"
output: "gpu_0/masks_int32"
output: "gpu_0/rois_fpn2"
output: "gpu_0/rois_fpn3"
output: "gpu_0/rois_fpn4"
output: "gpu_0/rois_fpn5"
output: "gpu_0/rois_idx_restore_int32"
output: "gpu_0/mask_rois_fpn2"
output: "gpu_0/mask_rois_fpn3"
output: "gpu_0/mask_rois_fpn4"
output: "gpu_0/mask_rois_fpn5"
output: "gpu_0/mask_rois_idx_restore_int32"
name: "CollectAndDistributeFpnRpnProposalsOp:gpu_0/rpn_rois_fpn2,gpu_0/rpn_rois_fpn3,gpu_0/rpn_rois_fpn4,gpu_0/rpn_rois_fpn5,gpu_0/rpn_rois_fpn6,gpu_0/rpn_roi_probs_fpn2,gpu_0/rpn_roi_probs_fpn3,gpu_0/rpn_roi_probs_fpn4,gpu_0/rpn_roi_probs_fpn5,gpu_0/rpn_roi_probs_fpn6,gpu_0/roidb,gpu_0/im_info"
type: "Python"
arg {
  name: "grad_input_indices"
}
arg {
  name: "token"
  s: "forward:5"
}
arg {
  name: "grad_output_indices"
}
device_option {
  device_type: 1
  cuda_gpu_id: 0
}

### Detailed steps to reproduce
Under the mask_rcnn_heads.py add_mask_rcnn_losses function, I changed the SigmoidCrossEntropyLoss to SquaredL2Distance loss, and averaged it for the final loss. I've made sure that CLS_SPECIFIC_MASK is false, so the output layer of the logits should be 1*M*M for each roi.
```
The command that you ran
```

### System information

* Operating system: Ubuntu 16.04 LTS
* GPU models (for all devices if they are not all the same): single 1080ti

**Comment by xieshuqin** [comment]
Ran into same problem. Any new progress?

**Comment by xieshuqin** [comment]
After diving into the caffe2 `core.py`, we found the problem. 

When calling the function `_GenerateGradientsForForwardOp` in line 923, if the `g_output` are not all `None`, it must register for the gradient in `g_output`. 
The different between `SquaredL2Distance` and `SigmoidCrossEntropyLoss` is that `SigmoidCrossEntropyLoss([X, Y], 'loss_sigm')` only returned gradient with respect to `X`, while `SquaredL2Distance([X,Y], 'loss_l2')` returns the gradient for both `X` and `Y`. 

Therefore, when using `SquaredL2Distance`, the gradient for `masks_int32` in the `CollectAndDistributeFpnRpnProposalsOp` will not be a `None`, while in `SigmoidCrossEntropyLoss`, the gradient for `masks_int32` is a `None`. That's why the error occurs.

**Comment by rbgirshick** [comment]
See #353; use `StopGradient`.
