### ISSUE TITLE
Couldn't download the model through --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl 

### ISSUE THREAD

**Issue by AutomanHan** [facebookresearch/Detectron#229]
I try to run:
python2 tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo

The error is :
Traceback (most recent call last):
  File "tools/infer_simple.py", line 147, in <module>
    main(args)
  File "tools/infer_simple.py", line 98, in main
    assert_and_infer_cfg()
  File "/home/conghan/Code/clonecaffe2/detectron/lib/core/config.py", line 1018, in assert_and_infer_cfg
    cache_cfg_urls()
  File "/home/conghan/Code/clonecaffe2/detectron/lib/core/config.py", line 1025, in cache_cfg_urls
    __C.TRAIN.WEIGHTS = cache_url(__C.TRAIN.WEIGHTS, __C.DOWNLOAD_CACHE)
  File "/home/conghan/Code/clonecaffe2/detectron/lib/utils/io.py", line 60, in cache_url
    assert_cache_file_is_ok(url, cache_file_path)
  File "/home/conghan/Code/clonecaffe2/detectron/lib/utils/io.py", line 78, in assert_cache_file_is_ok
    ref_md5sum = _get_reference_md5sum(url)
  File "/home/conghan/Code/clonecaffe2/detectron/lib/utils/io.py", line 143, in _get_reference_md5sum
    md5sum = urllib2.urlopen(url_md5sum).read().strip()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

I think that my server can not connect the url. Can I download the model locally to load it? If it works, what should I download and where to save it.

**Comment by pingjunLi** [comment]
you can download the model locally and put it to the place anywhereand to load it.It will work well!

that's what I did:
python2 tools/infer_simple.py 
--cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml 
--output-dir /tmp/detectron-visualizations 
--image-ext jpg 
--wts /data/xiaobing.wang/pingjun.li/Detectron-master/models/e2e_keypoint_rcnn_R-101-FPN_s1x.pkl
demo

and change 'cfg' to:
TRAIN:
  WEIGHTS: /data/xiaobing.wang/pingjun.li/Detectron-master/models/ImageNetPretrained/R-50.pkl(You Can Download it)
  DATASETS: ('keypoints_coco_2014_train', 'keypoints_coco_2014_valminusminival')
  SCALES: (640, 672, 704, 736, 768, 800)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level

**Comment by dulangaheshan** [comment]
you can download models from [here](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#person-specific-rpn-baselines)
