### ISSUE TITLE
Error on while running test_spatial_narrow_as_op.py

### ISSUE THREAD

**Issue by soumenms2015** [facebookresearch/Detectron#242]
Hello I am trying to install detectron by running test_spatial_narrow_op.py. I am getting follwoing error.
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-08

(mismatch 100.0%)
 x: array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],...
 y: array([[[[ 5.894372e-01,  2.964771e-01, -1.897605e+00, ...,
          -2.382408e-01,  1.334857e+00, -1.133502e+00],
         [-7.725763e-01,  7.037065e-03,  3.188964e-01, ...,...

======================================================================
FAIL: test_small_forward_and_gradient (__main__.SpatialNarrowAsOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_spatial_narrow_as_op.py", line 59, in test_small_forward_and_gradient
    self._run_test(A, B, check_grad=True)
  File "tests/test_spatial_narrow_as_op.py", line 54, in _run_test
    np.testing.assert_allclose(C, C_ref, rtol=1e-5, atol=1e-08)
  File ".../anaconda2/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "..../anaconda2/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-08

(mismatch 100.0%)
 x: array([[[[0., 0.],
         [0., 0.]],
...
 y: array([[[[ 1.589158, -1.511063],
         [-0.564949, -1.795473]],
...

----------------------------------------------------------------------
Ran 3 tests in 2.371s

FAILED (failures=2)
Any idea?

**Comment by mks0601** [comment]
how did you solve this issue?
