### ISSUE TITLE
IndexError: list index out of range when training detectron on my custom data

### ISSUE THREAD

**Issue by LightningChan** [facebookresearch/Detectron#256]
Hi，seek for help!
I train detectron on LIP dataset，and I have convert annotations to coco-like json.
I use  configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_1x.yaml
Then，I run to this problem: 

INFO train_net_my.py: 253: Loading dataset: ('lip_val',)
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
INFO roidb.py:  49: Appending horizontally-flipped training examples...
INFO roidb.py:  51: Loaded dataset: lip_val
INFO roidb.py: 135: Filtered 0 roidb entries: 0 -> 0
INFO roidb.py:  67: Computing bounding-box regression targets...
INFO roidb.py:  69: done
Traceback (most recent call last):
  File "tools/train_net_my.py", line 281, in <module>
    main()
  File "tools/train_net_my.py", line 119, in main
    checkpoints = train_model()
  File "tools/train_net_my.py", line 133, in train_model
    setup_model_for_training(model, output_dir)
  File "tools/train_net_my.py", line 231, in setup_model_for_training
    add_model_training_inputs(model)
  File "tools/train_net_my.py", line 255, in add_model_training_inputs
    cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES
  File "/work/detectron/lib/datasets/roidb.py", line 71, in combined_roidb_for_training
    _compute_and_log_stats(roidb)
  File "/work/detectron/lib/datasets/roidb.py", line 180, in _compute_and_log_stats
    classes = roidb[0]['dataset'].classes
IndexError: list index out of range

Hope for your suggestions!

**Comment by roman12zhmud** [comment]
ПРИВЕТ СПАСИБО ЗА ПРЕДЛОЖЕНИЕ

**Comment by 994374821** [comment]
How to convert the annotations of LIP dataset to coco-like json? thank you!

**Comment by Houd1ny** [comment]
@LightningChan  what was the problem?
