### ISSUE TITLE
How to train for just one class?

### ISSUE THREAD

**Issue by Vivianyzw** [facebookresearch/Detectron#300]
I have a set of training data for vehicle. I have changed NUM CLASSES from 21 to 2 in training yaml file. But I got this error like this:
```
Traceback (most recent call last):
  File "tools/train_net.py", line 358, in <module>
    main()
  File "tools/train_net.py", line 196, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 210, in train_model
    setup_model_for_training(model, output_dir)
  File "tools/train_net.py", line 308, in setup_model_for_training
    add_model_training_inputs(model)
  File "tools/train_net.py", line 332, in add_model_training_inputs
    cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES
  File "/mnt/data1/detectron/lib/datasets/roidb.py", line 71, in combined_roidb_for_training
    _compute_and_log_stats(roidb)
  File "/mnt/data1/detectron/lib/datasets/roidb.py", line 180, in _compute_and_log_stats
    classes = roidb[0]['dataset'].classes
IndexError: list index out of range
```
Could you please tell me how to deal with this problem? Thanks in advance!

**Comment by Vivianyzw** [comment]
I found something strange here:
```
INFO roidb.py:  49: Appending horizontally-flipped training examples...
INFO roidb.py:  51: Loaded dataset: voc_2012_trainval
INFO roidb.py: 136: Filtered 0 roidb entries: 2000 -> 2000
INFO roidb.py:  67: Computing bounding-box regression targets...
INFO roidb.py:  69: done
INFO roidb.py: 192: Ground-truth class histogram:
INFO roidb.py: 196: 0__background__: 0
INFO roidb.py: 196: 1       vehicle: 0
INFO roidb.py: 197: --------------
INFO roidb.py: 200:          total: 0
INFO train_net.py: 334: 2000 roidb entries
```
There is no roi for vehicle class.
This is the voc2007 result:
```
 Computing bounding-box regression targets...
INFO roidb.py:  69: done
INFO roidb.py: 192: Ground-truth class histogram:
INFO roidb.py: 196: 0__background__: 0
INFO roidb.py: 196: 1     aeroplane: 302
INFO roidb.py: 196: 2       bicycle: 352
INFO roidb.py: 196: 3          bird: 486
INFO roidb.py: 196: 4          boat: 280
INFO roidb.py: 196: 5        bottle: 506
INFO roidb.py: 196: 6           bus: 230
INFO roidb.py: 196: 7           car: 1250
INFO roidb.py: 196: 8           cat: 372
INFO roidb.py: 196: 9         chair: 800
INFO roidb.py: 196: 10           cow: 272
INFO roidb.py: 196: 11   diningtable: 206
INFO roidb.py: 196: 12           dog: 506
INFO roidb.py: 196: 13         horse: 364
INFO roidb.py: 196: 14     motorbike: 334
INFO roidb.py: 196: 15        person: 4716
INFO roidb.py: 196: 16   pottedplant: 496
INFO roidb.py: 196: 17         sheep: 260
INFO roidb.py: 196: 18          sofa: 248
INFO roidb.py: 196: 19         train: 290
INFO roidb.py: 196: 20     tvmonitor: 332
INFO roidb.py: 197: --------------
INFO roidb.py: 200:          total: 12602
INFO train_net.py: 334: 5002 roidb entries
```
my json file is like this:
```
{"segmentation": [[469, 494, 485, 482, 497, 496, 511, 501, 521, 525, 538, 560, 552, 603, 571, 660, 580, 685, 587, 719, 593, 765, 593, 816, 595, 860, 593, 885, 609, 886, 615, 928, 607, 938, 595, 941, 594, 965, 583, 973, 585, 1024, 584, 1061, 575, 1076, 570, 1137, 574, 1166, 574, 1217, 571, 1270, 567, 1334, 552, 1357, 484, 1358, 475, 1343, 472, 1326, 453, 1325, 415, 1328, 351, 1326, 314, 1331, 255, 1331, 219, 1332, 175, 1330, 103, 1328, 78, 1327, 75, 1344, 72, 1362, 19, 1362, 9, 1347, 0, 1290, 0, 1055, 6, 1029, 3, 1012, 13, 1004, 28, 965, 14, 949, 0, 943, 0, 897, 28, 899, 40, 914, 55, 858, 85, 763, 85, 740, 98, 709, 106, 654, 121, 610, 129, 576, 145, 535, 160, 509, 167, 502, 182, 490, 195, 503]], "area": 441803.0, "iscrowd": 1, "image_id": "201800512", "bbox": [0, 482, 615, 880], "category_id": 1, "id": "201800512"}
"categories": [{"supercategory": "vehicle", "id": 1, "name": "vehicle"}]
```
I am quite confused of what is wrong with my annotation files.

**Comment by AutomanHan** [comment]
@Vivianyzw I meet the same issue. I need to detect football in the picture. There is only one class. I add another class annotation, which is not exist in my data set, to the .json file and the issue is solved. And the data set can be trained, but there is some errors. Could you tell me how you solve this issue?
![image](https://user-images.githubusercontent.com/24837080/37650599-5cc95b98-2c70-11e8-83b6-197eddd08935.png)
