### ISSUE TITLE
fail to run Infer_simple.py with my own weight pkl file.

### ISSUE THREAD

**Issue by Si-YuWang** [facebookresearch/Detectron#316]
I made it to use Detectron to train over my own datasets and save the weights (.pkl file) in my directory and the bboxes are pretty good. Then I wanted to use the .pkl file to run infer_simple.py, and I failed in this step. 
Following are my commands:
for training : 
```
python2 tools/train_net.py \
    --cfg configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml \
    OUTPUT_DIR  /home/siyu/Detectron/train_output 
```

for infering: 
```
python2 tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-50-FPN_2x.yaml \
    --output-dir /home/siyu/Detectron/Arrows
    --image-ext png \
    --wts 
 /home/siyu/Detectron/train_output/train/coco_2014_train/generalized_rcnn/model_iter59999.pkl   \
    demo
```
And the error is:
```
INFO net.py:  57: Loading weights from: train_output/train/coco_2014_train/generalized_rcnn/model_iter59999.pkl
INFO net.py:  86: fcn1_w not found
INFO net.py:  86: fcn1_b not found
INFO net.py:  86: fcn2_w not found
INFO net.py:  86: fcn2_b not found
INFO net.py:  86: fcn3_w not found
INFO net.py:  86: fcn3_b not found
INFO net.py:  86: fcn4_w not found
INFO net.py:  86: fcn4_b not found
INFO net.py:  86: conv5_mask_w not found
INFO net.py:  86: conv5_mask_b not found
INFO net.py:  86: mask_fcn_logits_w not found
INFO net.py:  86: mask_fcn_logits_b not found
I0324 15:34:48.657366 79040 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 8.9349e-05 secs
I0324 15:34:48.657536 79040 net_dag.cc:61] Number of parallel execution chains 63 Number of operators = 232
I0324 15:34:48.669070 79040 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 7.4556e-05 secs
I0324 15:34:48.669200 79040 net_dag.cc:61] Number of parallel execution chains 30 Number of operators = 188
I0324 15:34:48.670559 79040 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 1.0068e-05 secs
I0324 15:34:48.670590 79040 net_dag.cc:61] Number of parallel execution chains 5 Number of operators = 18
INFO infer_simple.py: 111: Processing demo/1.png -> /home/siyu/Detectron/Arrows/1.png.pdf
E0324 15:34:49.744932 79130 net_dag.cc:203] Exception from operator '' (type 'Concat'): caffe2::EnforceNotMet: [enforce fail at blob.h:97] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/_[mask]_fcn1_w.
Error from operator:
input: "gpu_0/_[mask]_roi_feat" input: "gpu_0/_[mask]_fcn1_w" input: "gpu_0/_[mask]_fcn1_b" output: "gpu_0/_[mask]_fcn1" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN" debug_info: "  File \"tools/infer_simple.py\", line 147, in <module>\n    main(args)\n  File \"tools/infer_simple.py\", line 99, in main\n    model = infer_engine.initialize_model_from_cfg()\n  File \"/home/siyu/Detectron/lib/core/test_engine.py\", line 266, in initialize_model_from_cfg\n    model = model_builder.create(cfg.MODEL.TYPE, train=False, gpu_id=gpu_id)\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 124, in create\n    return get_func(model_type_func)(model)\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 89, in generalized_rcnn\n    freeze_conv_body=cfg.TRAIN.FREEZE_CONV_BODY\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 229, in build_generic_detection_model\n    optim.build_data_parallel_model(model, _single_gpu_build_func)\n  File \"/home/siyu/Detectron/lib/modeling/optimizer.py\", line 54, in build_data_parallel_model\n    single_gpu_build_func(model)\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 210, in _single_gpu_build_func\n    spatial_scale_conv\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 272, in _add_roi_mask_head\n    model, blob_in, dim_in, spatial_scale_in\n  File \"/home/siyu/Detectron/lib/modeling/mask_rcnn_heads.py\", line 113, in mask_rcnn_fcn_head_v1up4convs\n    model, blob_in, dim_in, spatial_scale, 4\n  File \"/home/siyu/Detectron/lib/modeling/mask_rcnn_heads.py\", line 151, in mask_rcnn_fcn_head_v1upXconvs\n    bias_init=(\'ConstantFill\', {\'value\': 0.})\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/cnn.py\", line 112, in Conv\n    **kwargs\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/brew.py\", line 121, in scope_wrapper\n    return func(*args, **new_kwargs)\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/helpers/conv.py\", line 201, in conv\n    group, transform_inputs, **kwargs)\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/helpers/conv.py\", line 154, in _ConvBase\n    **kwargs)\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/core.py\", line 2047, in <lambda>\n    op_type, *args, **kwargs)\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/core.py\", line 2024, in _CreateAndAddToSelf\n    op = CreateOperator(op_type, inputs, outputs, **kwargs)\n"
Original python traceback for operator 6 in network `mask_net` in exception above (most recent call last):
Traceback (most recent call last):
  File "tools/infer_simple.py", line 147, in <module>
    main(args)
  File "tools/infer_simple.py", line 117, in main
    model, im, None, timers=timers
  File "/home/siyu/Detectron/lib/core/test.py", line 81, in im_detect_all
    masks = im_detect_mask(model, im_scales, boxes)
  File "/home/siyu/Detectron/lib/core/test.py", line 395, in im_detect_mask
    workspace.RunNet(model.mask_net.Proto().name)
  File "/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/workspace.py", line 230, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/workspace.py", line 192, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at blob.h:97] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/_[mask]_fcn1_w.
Error from operator:
input: "gpu_0/_[mask]_roi_feat" input: "gpu_0/_[mask]_fcn1_w" input: "gpu_0/_[mask]_fcn1_b" output: "gpu_0/_[mask]_fcn1" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN" debug_info: "  File \"tools/infer_simple.py\", line 147, in <module>\n    main(args)\n  File \"tools/infer_simple.py\", line 99, in main\n    model = infer_engine.initialize_model_from_cfg()\n  File \"/home/siyu/Detectron/lib/core/test_engine.py\", line 266, in initialize_model_from_cfg\n    model = model_builder.create(cfg.MODEL.TYPE, train=False, gpu_id=gpu_id)\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 124, in create\n    return get_func(model_type_func)(model)\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 89, in generalized_rcnn\n    freeze_conv_body=cfg.TRAIN.FREEZE_CONV_BODY\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 229, in build_generic_detection_model\n    optim.build_data_parallel_model(model, _single_gpu_build_func)\n  File \"/home/siyu/Detectron/lib/modeling/optimizer.py\", line 54, in build_data_parallel_model\n    single_gpu_build_func(model)\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 210, in _single_gpu_build_func\n    spatial_scale_conv\n  File \"/home/siyu/Detectron/lib/modeling/model_builder.py\", line 272, in _add_roi_mask_head\n    model, blob_in, dim_in, spatial_scale_in\n  File \"/home/siyu/Detectron/lib/modeling/mask_rcnn_heads.py\", line 113, in mask_rcnn_fcn_head_v1up4convs\n    model, blob_in, dim_in, spatial_scale, 4\n  File \"/home/siyu/Detectron/lib/modeling/mask_rcnn_heads.py\", line 151, in mask_rcnn_fcn_head_v1upXconvs\n    bias_init=(\'ConstantFill\', {\'value\': 0.})\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/cnn.py\", line 112, in Conv\n    **kwargs\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/brew.py\", line 121, in scope_wrapper\n    return func(*args, **new_kwargs)\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/helpers/conv.py\", line 201, in conv\n    group, transform_inputs, **kwargs)\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/helpers/conv.py\", line 154, in _ConvBase\n    **kwargs)\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/core.py\", line 2047, in <lambda>\n    op_type, *args, **kwargs)\n  File \"/home/siyu/anaconda3/envs/python27/lib/python2.7/site-packages/caffe2/python/core.py\", line 2024, in _CreateAndAddToSelf\n    op = CreateOperator(op_type, inputs, outputs, **kwargs)\n"

```
I guess I'm wrong confusing different models when training and inferring, but I really can figure out where I did wrong.

**Comment by AutomanHan** [comment]
@Ykimy I meet the same error at the beginning. 
`RuntimeError: [enforce fail at blob.h:97] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .`
My model file is not consistent with the train net. I change the model file and it is solved. 
#237 may give you more suggestions.

**Comment by micyng** [comment]
I had the exactly same error when running infer_simple.py
 
What I did:

* Adjusted value of NUM_CLASSES in configs/tutorial_1gpu...yaml 
* Also the value of NUM_CLASSES in configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml

Both of these two values are real class count of my own datasets plus one (for background)

Meanwhile, after training process done, the  test_model call also finished without error, which is line 122 of tools/train_net.py

**Comment by micyng** [comment]
Besides, I also downloaded the r101.pkl and r50.pkl to local machine
And their md5sum both correct

So I think this issue may be not same cause as #237

**Comment by rbgirshick** [comment]
It looks like you're mixing a config file for Mask R-CNN with a model that was trained without masks.

**Comment by vtgist** [comment]
@Si-YuWang You have used the faster_rcnn config config file to train, and the mask_rcnn config file to infer.
