### ISSUE TITLE
run python2 $DETECTRON/tests/test_spatial_narrow_as_op.py error:

### ISSUE THREAD

**Issue by datamonday** [facebookresearch/Detectron#346]
when I run python2 $DETECTRON/tests/test_spatial_narrow_as_op.py ,I got this tips:

Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
Traceback (most recent call last):
  File "./tests/test_spatial_narrow_as_op.py", line 88, in <module>
    utils.c2.import_detectron_ops()
  File "/home/chopin/anaconda3/envs/caffe2/caffe2/build/detectron/lib/utils/c2.py", line 42, in import_detectron_ops
    dyndep.InitOpsLibrary(detectron_ops_lib)
  File "/home/chopin/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/home/chopin/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/home/chopin/anaconda3/envs/caffe2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E

I create enviroment in anaconda3 with python=2.7 and set up the caffe2 successfully.
 cuda  8.0 cudnn 7.1

what's wrong? I'm looking forward to your answer and thank you!

**Comment by datamonday** [comment]
I try to search libnccl.so.2 in my systerm,but it's none.And i find libnccl.so  libnccl.so.1  libnccl.so.1.3.4

**Comment by datamonday** [comment]
Got it! 

I export the python path like /home/chopin/anaconda3/envs/caffe2/caffe2/build/caffe2/python to ~/.bashrc  and then pip install utils .

 Now, it's running! I hope this will help you.
