### ISSUE TITLE
AssertionError: Range subprocess failed (exit code: 126)

### ISSUE THREAD

**Issue by wuqi930907** [facebookresearch/Detectron#349]
Hi, when I attempted to train the coco datasets, I got an error:
/bin/sh: 1: /home/serversys006/Detectron/tools/test_net.py: Permission denied
Traceback (most recent call last):
  File "tools/train_net.py", line 281, in <module>
    main()
  File "tools/train_net.py", line 122, in main
    test_model(checkpoints['final'], args.multi_gpu_testing, args.opts)
  File "tools/train_net.py", line 277, in test_model
    test_net.main(multi_gpu_testing=multi_gpu_testing)
  File "/home/serversys006/Detectron/tools/test_net.py", line 98, in main
    output_dir, ind_range=ind_range, multi_gpu_testing=multi_gpu_testing
  File "/home/serversys006/Detectron/lib/core/test_engine.py", line 83, in run_inference
    results = parent_func(output_dir, multi_gpu=multi_gpu_testing)
  File "/home/serversys006/Detectron/lib/core/test_engine.py", line 103, in test_net_on_dataset
    num_images, output_dir
  File "/home/serversys006/Detectron/lib/core/test_engine.py", line 126, in multi_gpu_test_net_on_dataset
    'detection', num_images, binary, output_dir
  File "/home/serversys006/Detectron/lib/utils/subprocess.py", line 92, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home/serversys006/Detectron/lib/utils/subprocess.py", line 130, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 126)

The following is my script：（train.sh）
python2 tools/train_net.py \
    --multi-gpu-testing \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    OUTPUT_DIR train_results_mask

It looks like a permissions issue，but my command is "sudo train.sh" to use root permission.

Thanks

**Comment by rbgirshick** [comment]
Perhaps try `chmod -x tools/test_net.py` to make `test_net.py` executable if it is not already (it should be by default after a clean `git clone`).

**Comment by wuqi930907** [comment]
It's unbelievable that this is the problem.I'm surprised that train_net.py is also has no executive power to execut, but it works well. @rbgirshick
