### ISSUE TITLE
 status == CUDNN_STATUS_SUCCESS. 3 vs 0.  UDNN_STATUS_BAD_PARAM Error from operator

### ISSUE THREAD

**Issue by yubo-zhang** [facebookresearch/Detectron#351]
### Expected results

I successfully install the latest caffe2, and detectron. Running "./tests/test_spatial_narrow_as_op.py 
" works fun. However when I run the infer_simple example in GETTING_STARTED.md:

python2 tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo

The error occurs:
Traceback (most recent call last):
  File "tools/infer_simple.py", line 149, in <module>
    main(args)
  File "tools/infer_simple.py", line 119, in main
    model, im, None, timers=timers
  File "/home/action_detection/Detectron/lib/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/action_detection/Detectron/lib/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/home/caffe2s/caffe2/build/caffe2/python/workspace.py", line 215, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/caffe2s/caffe2/build/caffe2/python/workspace.py", line 177, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at conv_op_cudnn.cc:302] status == CUDNN_STATUS_SUCCESS. 3 vs 0. , Error at: /home/caffe2s/caffe2/caffe2/operators/conv_op_cudnn.cc:302: CUDNN_STATUS_BAD_PARAM Error from operator: 
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"

### System information

* Operating system: Ubuntu 14.04
* CUDA version:cuda 8.0
* cuDNN version: cudnn 6.0.21
* GPU models :1080Ti *4
* `python --version` : 2.7

I have another older version of caffe2 which doesn't include detectron.  It works fine for other projects. Also one or multiple gpus all ends up with this error. I have searched all over the possible answers on internet and couldn't figure out what happened here. Could anyone help me? Thanks so much!!

**Comment by cr-hxfan** [comment]
Hi, did you solve it?    I have the same issue.

**Comment by gadcam** [comment]
If you google <code>status == CUDNN_STATUS_SUCCESS. 3 vs 0</code> you will often find that doing a clean install/updating cuDNN can help.
So for what it is worth, I would try to (re-?)install the latest cuDNN before anything else.

**Comment by cr-hxfan** [comment]
Thanks for your reply @gadcam .   I just upgraded my cudnn version to 7.05 (latest, for cuda 8.0).
But the issue is still the same.
Any other possible solutions?
