### ISSUE TITLE
Not able to run GPU for Caffe2/Detectron

### ISSUE THREAD

**Issue by Flock1** [facebookresearch/Detectron#370]
* Operating system: Ubuntu 16.04
* GPU models (for all devices if they are not all the same): GTX 1080 8GB
* python --version: 2.7
Caffe2/Detectron
OS: Ubuntu 16.04
Python: 2.7
GPU: GTX 1080
gcc version: 5.4.0

I have installed CUDA, Cudnn and nccl in a conda environment and followed the steps in the installation file. I used conda (as mentioned) to install caffe2 and other libraries.

`conda install -c caffe2 caffe2-cuda9.0-cudnn7`

Then, to see if GPU is working, I get the following:
`WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)`

I don't know what I am doing wrong or something I am missing. Please let me know.

**Comment by ambigus9** [comment]
Please try with Docker installation, and then install [NVIDIA Docker](https://github.com/NVIDIA/nvidia-docker) After that try running inside the docker.

**Comment by YefeiGao** [comment]
u should install nccl2 and make sure add the path contain libnccl.so.2 to ur $LD_LIBRARY_PATH to solve that @Flock1

**Comment by Flock1** [comment]
Worked!!!

**Comment by Flock1** [comment]
@ambigus9, I tried docker and ran 
`nvidia-docker run -it caffe2ai/caffe2:latest python -m caffe2.python.operator_test.relu_op_test` in my conda caffe2 env and got the following output:
```
Ran 1 test in 4.695s

OK
``` 

So I guess it worked. But I don't know how to use docker for further applications. Any suggestions?

**Comment by ambigus9** [comment]
@Flock1 What you want to do? Maybe you can start running the examples: 

```
python tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo
```
If you have low VRAM (like 4 GB) of your GPU, please try something more easier as follows:

```
python2 tools/infer_simple.py \
  --cfg configs/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml \
  --output-dir /tmp/detectron-visualizations \
  --image-ext jpg \
  --wts https://s3-us-west-2.amazonaws.com/detectron/35857389/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml.01_37_22.KSeq0b5q/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl \
  demo
```

**Comment by Flock1** [comment]
@ambigus9, I want to do Semantic Seg on an image and possibly videos and I want to use my GPU for it. As shown in a test above, it failed and I am guessing that GPU is still now working. So I want to avoid that.

**Comment by ambigus9** [comment]
@Flock1 Did you tried the examples above?

**Comment by Flock1** [comment]
@ambigus9, no. I'll try it in a couple of hours. But does it use the GPU for segmentation? Also, why do you think the test failed?

**Comment by ambigus9** [comment]
@Flock1 Could you please try the test inside the Docker?

**Comment by Flock1** [comment]
@ambigus9, Sure. I will try that.

**Comment by Flock1** [comment]
Hi,
I am getting a new error now when I run `python2 $DETECTRON/tests/test_spatial_narrow_as_op.py`:

```
E0421 16:01:19.569461 10741 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0421 16:01:19.569483 10741 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0421 16:01:19.569500 10741 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid device ordinal 
*** Aborted at 1524306679 (unix time) try "date -d @1524306679" if you are using GNU date ***
PC: @     0x7fe69f7ea428 gsignal
*** SIGABRT (@0x3e8000029f5) received by PID 10741 (TID 0x7fe6a0a65700) from PID 10741; stack trace: ***
    @     0x7fe6a02a0390 (unknown)
    @     0x7fe69f7ea428 gsignal
    @     0x7fe69f7ec02a abort
    @     0x7fe69151cb39 __gnu_cxx::__verbose_terminate_handler()
    @     0x7fe69151b1fb __cxxabiv1::__terminate()
    @     0x7fe69151a640 __cxa_call_terminate
    @     0x7fe69151ae6f __gxx_personality_v0
    @     0x7fe69a4b8564 _Unwind_RaiseException_Phase2
    @     0x7fe69a4b881d _Unwind_RaiseException
    @     0x7fe69151b409 __cxa_throw
    @     0x7fe68f6c2b89 caffe2::CUDAContext::~CUDAContext()
    @     0x7fe68f84e52e caffe2::Operator<>::~Operator()
    @     0x7fe6564abb0a caffe2::SpatialNarrowAsOp<>::~SpatialNarrowAsOp()
    @     0x7fe6564abb3a caffe2::SpatialNarrowAsOp<>::~SpatialNarrowAsOp()
    @     0x7fe68e694acf caffe2::Workspace::RunOperatorOnce()
    @     0x7fe69094feea _ZZN6caffe26python16addGlobalMethodsERN8pybind116moduleEENKUlRKNS1_5bytesEE26_clES6_.isra.2766.constprop.2816
    @     0x7fe690950185 _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNS_5bytesEE26_bJS8_EJNS_4nameENS_5scopeENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESQ_
    @     0x7fe69097a4bd pybind11::cpp_function::dispatcher()
    @     0x7fe6a058e645 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a058d4b2 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a058d4b2 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a058d4b2 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a05190f7 function_call
    @     0x7fe6a04f47a3 PyObject_Call
    @     0x7fe6a0589500 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a051900a function_call
    @     0x7fe6a04f47a3 PyObject_Call
Aborted (core dumped)

```

Can you help me with this?

**Comment by Flock1** [comment]
@ambigus9, I tried the example you sent me to try. I go the following error:
`ImportError: No module named pycocotools.mask`

**Comment by ambigus9** [comment]
@Flock1 Could you please tell me if you are running inside the Docker? Please be careful, you must run the docker with Nvidia-Docker it as follows: `nvidia-docker run -it <IMAGE ID> /bin/bash`

And, when you are inside the docker, you must be inside of detectron folder and then run:

`python tests/test_spatial_narrow_as_op.py`

**Comment by Flock1** [comment]
@ambigus9, I'm running it in conda environment. I'm not very experienced with docker so learning it for now.

**Comment by ambigus9** [comment]
@Flock1 Sure, If you need help, just ask.

**Comment by Flock1** [comment]
@ambigus9, thanks for that. But do let me know why conda environment is messing up. What I'm thinking is I tried to install caffe2 from source. So could that be an issue?

**Comment by ambigus9** [comment]
@Flock1 On my experience i must confess that currently i think is a issue with the binary provided by Caffe2, because as you the same as you, i tried building from source, setting the variable enviroment, and it didn't work, you can check this [steps](https://github.com/facebookresearch/Detectron/issues/139#issuecomment-383252626)

**Comment by Flock1** [comment]
@YefeiGao, can you help with the issue?

**Comment by Flock1** [comment]
@ambigus9, I ran it in docker. For `python2 test_spatial_narrow_as_op.py`, I am getting the following:

```
Traceback (most recent call last):
  File "test_spatial_narrow_as_op.py", line 88, in <module>
    utils.c2.import_detectron_ops()
  File "/detectron/lib/utils/c2.py", line 41, in import_detectron_ops
    detectron_ops_lib = envu.get_detectron_ops_lib()
  File "/detectron/lib/utils/env.py", line 71, in get_detectron_ops_lib
    ('Detectron ops lib not found; make sure that your Caffe2 '
AssertionError: Detectron ops lib not found; make sure that your Caffe2 version includes Detectron module

```

**Comment by ambigus9** [comment]
@Flock1 You are inside the docker and also inside `/detectron`  folder?

**Comment by Flock1** [comment]
@ambigus9, yes. I'm in docker now. Also, can you help me with the errors from conda environment?

**Comment by ambigus9** [comment]
@Flock1 Are you running the docker a conda Enviroment?

**Comment by Flock1** [comment]
@ambigus9, no. I'm using a conda environment.

**Comment by ambigus9** [comment]
@Flock1 Could you please try without conda enviroment?

**Comment by ambigus9** [comment]
@Flock1 How you make the Docker image? 

Following the original steps:

```
cd $DETECTRON/docker
docker build -t detectron:c2-cuda9-cudnn7 .
```

Running:

```
nvidia-docker run --rm -it detectron:c2-cuda9-cudnn7 python2 tests/test_batch_permutation_op.py
```

**Comment by Flock1** [comment]
@ambigus9, I didn't follow these steps. Wow, that's my bad. I'll try that today. Thanks

**Comment by Flock1** [comment]
@ambigus9, can you also tell me how to delete caffe2 if I installed it from source?

**Comment by ambigus9** [comment]
@Flock1 You're welcome! Anything you need just let me know.

**Comment by ambigus9** [comment]
@Flock1 At the moment i don't know how to do that. May me you can find any inspiration from the original source [Pytorch](https://github.com/pytorch/pytorch/)

**Comment by Flock1** [comment]
@ambigus9, the docker installation worked!! However, when I ran the detectron code for showing some demo, I got the following:

```
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
E0425 12:02:28.544355   272 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0425 12:02:28.544375   272 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0425 12:02:28.544394   272 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO io.py:  67: Downloading remote file https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl to /tmp/detectron-download-cache/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl
```

And it's working very slowly. So is my GPU being used?

**Comment by Flock1** [comment]
@ambigus9, yeah. I realized that the internet was very slow, so downloading the model was taking time. I think it's finally done through docker.

**Comment by ambigus9** [comment]
@Flock1 Perfect! Anything you need i will help you.

**Comment by Flock1** [comment]
@ambigus9, let me know where I should contact you?

**Comment by gadcam** [comment]
I think this issue can be closed as the problem seems to be solved.

**Comment by garvita-tiwari** [comment]
I dont have administrative rights on my system. So I am installing
conda install -c anaconda cudnn
conda install -c anaocnda nccl or conda installl -c pytorch nccl2 
cconda install -c caffe2 caffe2-cuda9.0-cudnn7
but I get the same error
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode. WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory Segmentation fault (core dumped)

Is it because I am installing using conda?

**Comment by ambigus9** [comment]
@garvita-tiwari Did you tried using [Dockerfile](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#docker-image) instructions?

**Comment by ambigus9** [comment]
@garvita-tiwari Currently I recommend Docker, Maybe you can try to install Docker on your System.

**Comment by Flock1** [comment]
@garvita-tiwari, the `WARNING` that you're getting is because it's not able to locate the file. You'll need to locate the file on your system and add it to your `.bashrc` file. 
You can also try to use conda environments as mentioned on the website.  
Docker will also work.

**Comment by Flock1** [comment]
@garvita-tiwari, the `WARNING` that you're getting is because it's not able to locate the file. You'll need to locate the file on your system and add it to your `.bashrc` file.
You can also try to use conda environments as mentioned on the website.
Docker will also work.

**Comment by biswajitcsecu** [comment]
blah   blah
