### ISSUE TITLE
Test in my own dataset,  use 【 e2e_faster_rcnn_R-101-FPN_1x.yaml 】

### ISSUE THREAD

**Issue by jobbofhe** [facebookresearch/Detectron#371]
Thank you very much for the great project! 
I used  e2e_faster_rcnn_R-101-FPN_1x.yaml  and downloaded model MSRA/R-101.pkl to local. 

 and  run：

` python tools/infer_simple.py     --cfg configs/12_2017_baselines/e2e_faster_rcnn_R-101-FPN_1x.yaml     --output-dir /tmp/detectron-visualizations     --image-ext jpg     --wts /tmp/detectron-download-cache/ImageNetPretrained/MSRA/R-101.pkl     demo/19064748793_bb942deea1_k.jpg`

get error：

`
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
E0417 10:59:37.916357 13936 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0417 10:59:37.916386 13936 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0417 10:59:37.916393 13936 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.

WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  57: Loading weights from: /tmp/detectron-download-cache/ImageNetPretrained/MSRA/R-101.pkl
INFO net.py:  86: fpn_inner_res5_2_sum_w not found
INFO net.py:  86: fpn_inner_res5_2_sum_b not found
INFO net.py:  86: fpn_inner_res4_22_sum_lateral_w not found
INFO net.py:  86: fpn_inner_res4_22_sum_lateral_b not found
INFO net.py:  86: fpn_inner_res3_3_sum_lateral_w not found
INFO net.py:  86: fpn_inner_res3_3_sum_lateral_b not found
INFO net.py:  86: fpn_inner_res2_2_sum_lateral_w not found
INFO net.py:  86: fpn_inner_res2_2_sum_lateral_b not found
INFO net.py:  86: fpn_res5_2_sum_w not found
INFO net.py:  86: fpn_res5_2_sum_b not found
INFO net.py:  86: fpn_res4_22_sum_w not found
INFO net.py:  86: fpn_res4_22_sum_b not found
INFO net.py:  86: fpn_res3_3_sum_w not found
INFO net.py:  86: fpn_res3_3_sum_b not found
INFO net.py:  86: fpn_res2_2_sum_w not found
INFO net.py:  86: fpn_res2_2_sum_b not found
INFO net.py:  86: conv_rpn_fpn2_w not found
INFO net.py:  86: conv_rpn_fpn2_b not found
INFO net.py:  86: rpn_cls_logits_fpn2_w not found
INFO net.py:  86: rpn_cls_logits_fpn2_b not found
INFO net.py:  86: rpn_bbox_pred_fpn2_w not found
INFO net.py:  86: rpn_bbox_pred_fpn2_b not found
INFO net.py:  86: fc6_w not found
INFO net.py:  86: fc6_b not found
INFO net.py:  86: fc7_w not found
INFO net.py:  86: fc7_b not found
INFO net.py:  86: cls_score_w not found
INFO net.py:  86: cls_score_b not found
INFO net.py:  86: bbox_pred_w not found
INFO net.py:  86: bbox_pred_b not found
I0417 10:59:39.867803 13936 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000142469 secs
I0417 10:59:39.868062 13936 net_dag.cc:46] Number of parallel execution chains 63 Number of operators = 402
I0417 10:59:39.886636 13936 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000158435 secs
I0417 10:59:39.886823 13936 net_dag.cc:46] Number of parallel execution chains 30 Number of operators = 358
INFO infer_simple.py: 115: Processing demo/19064748793_bb942deea1_k.jpg -> /tmp/detectron-visualizations/19064748793_bb942deea1_k.jpg
E0417 10:59:40.495563 13952 net_dag.cc:188] Exception from operator chain starting at '' (type 'Conv'): caffe2::EnforceNotMet: [enforce fail at blob.h:81] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/fpn_inner_res2_2_sum_lateral_w.
Error from operator: 
input: "gpu_0/res2_2_sum" input: "gpu_0/fpn_inner_res2_2_sum_lateral_w" input: "gpu_0/fpn_inner_res2_2_sum_lateral_b" output: "gpu_0/fpn_inner_res2_2_sum_lateral" name: "" type: "Conv" arg { name: "kernel" i: 1 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
Original python traceback for operator 350 in network `generalized_rcnn` in exception above (most recent call last):
  File "tools/infer_simple.py", line 154, in <module>
  File "tools/infer_simple.py", line 103, in main
  File "/icooper/dev/detectron/lib/core/test_engine.py", line 328, in initialize_model_from_cfg
  File "/icooper/dev/detectron/lib/modeling/model_builder.py", line 124, in create
  File "/icooper/dev/detectron/lib/modeling/model_builder.py", line 89, in generalized_rcnn
  File "/icooper/dev/detectron/lib/modeling/model_builder.py", line 229, in build_generic_detection_model
  File "/icooper/dev/detectron/lib/modeling/optimizer.py", line 54, in build_data_parallel_model
  File "/icooper/dev/detectron/lib/modeling/model_builder.py", line 169, in _single_gpu_build_func
  File "/icooper/dev/detectron/lib/modeling/FPN.py", line 62, in add_fpn_ResNet101_conv5_body
  File "/icooper/dev/detectron/lib/modeling/FPN.py", line 105, in add_fpn_onto_conv_body
  File "/icooper/dev/detectron/lib/modeling/FPN.py", line 166, in add_fpn
  File "/icooper/dev/detectron/lib/modeling/FPN.py", line 244, in add_topdown_lateral_module
  File "/root/.local/lib/python2.7/site-packages/caffe2/python/cnn.py", line 97, in Conv
  File "/root/.local/lib/python2.7/site-packages/caffe2/python/brew.py", line 106, in scope_wrapper
  File "/root/.local/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 186, in conv
  File "/root/.local/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 139, in _ConvBase
Traceback (most recent call last):
  File "tools/infer_simple.py", line 154, in <module>
    main(args)
  File "tools/infer_simple.py", line 121, in main
    model, im, None, timers=timers
  File "/icooper/dev/detectron/lib/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/icooper/dev/detectron/lib/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/root/.local/lib/python2.7/site-packages/caffe2/python/workspace.py", line 215, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/root/.local/lib/python2.7/site-packages/caffe2/python/workspace.py", line 177, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at blob.h:81] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/fpn_inner_res2_2_sum_lateral_w.
Error from operator: 
input: "gpu_0/res2_2_sum" input: "gpu_0/fpn_inner_res2_2_sum_lateral_w" input: "gpu_0/fpn_inner_res2_2_sum_lateral_b" output: "gpu_0/fpn_inner_res2_2_sum_lateral" name: "" type: "Conv" arg { name: "kernel" i: 1 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"`

**Comment by ppwwyyxx** [comment]
You're trying to load an ImageNet pretrained model. Instead you should download and load a FPN model.

**Comment by jobbofhe** [comment]
Oh, I see. Thank you!
