### ISSUE TITLE
Cannot train with multi-label

### ISSUE THREAD

**Issue by kevinlin311tw** [facebookresearch/Detectron#405]
I have a multi-label dataset (a bounding box is associated with multiple categories) and I want to finetune e2e faster-rcnn or mask-rcnn on this dataset.

After the survey, I understood that I need to modify (1) loss function, and (2) data inputs. For the first one, modifying loss function is a little bit straight forward. I think I can use sigmoid cross entropy or euclidean loss function. 

However, for the data inputs, I do not know how to modify the codes since current codes are built upon COCO API. COCO API does not support labels in vector format.

My training data looks like this:
``
[{u'segmentation': [], u'area': 25488.0, u'iscrowd': 0, u'ignore': 0, u'image_id': 2, u'bbox': [9, 54, 472, 54], u'category_id': [0,1,0,1], u'id': 1}, {u'segmentation': [], u'area': 36188.0, u'iscrowd': 0, u'ignore': 0, u'image_id': 2, u'bbox': [455, 332, 109, 332], u'category_id': [0,0,1,1], u'id': 2}]
``

I got the following errors when training with vector-based labels. 

> INFO memonger.py:  97: Memonger memory optimization took 0.0183930397034 secs
> I0501 23:22:52.474886 10813 context_gpu.cu:305] GPU 0: 153 MB
> I0501 23:22:52.474925 10813 context_gpu.cu:309] Total: 153 MB
> I0501 23:22:52.512137 10813 context_gpu.cu:305] GPU 0: 311 MB
> I0501 23:22:52.512181 10813 context_gpu.cu:309] Total: 311 MB
> INFO train.py: 179: Loading dataset: ('train_multilabel',)
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> Traceback (most recent call last):
>   File "tools/train_net.py", line 128, in <module>
>     main()
>   File "tools/train_net.py", line 110, in main
>     checkpoints = utils.train.train_model()
>   File "/data/caffe2/detectron/lib/utils/train.py", line 58, in train_model
>     setup_model_for_training(model, weights_file, output_dir)
>   File "/data/caffe2/detectron/lib/utils/train.py", line 157, in setup_model_for_training
>     add_model_training_inputs(model)
>   File "/data/caffe2/detectron/lib/utils/train.py", line 181, in add_model_training_inputs
>     cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES
>   File "/data/caffe2/detectron/lib/datasets/roidb.py", line 61, in combined_roidb_for_training
>     roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
>   File "/data/caffe2/detectron/lib/datasets/roidb.py", line 42, in get_roidb
>     ds = JsonDataset(dataset_name)
>   File "/data/caffe2/detectron/lib/datasets/json_dataset.py", line 69, in __init__
>     self.COCO = COCO(DATASETS[name][ANN_FN])
>   File "/usr/local/lib/python2.7/dist-packages/pycocotools/coco.py", line 88, in __init__
>     self.createIndex()
>   File "/usr/local/lib/python2.7/dist-packages/pycocotools/coco.py", line 110, in createIndex
>     catToImgs[ann['category_id']].append(ann['image_id'])
> TypeError: unhashable type: 'list'

Any idea to enable multi-label training using Detectron?

**Comment by information-security** [comment]
@kevinlin311tw 
> (1) Encode the multi-label to the integer label.
> (2) During mini-batch processing, decode the integer label to multi-label.

Are you suggesting something similar to what proposed in this tutorial: [Link](https://analyticsindiamag.com/multi-label-image-classification-with-tensorflow-keras/). I'm not an expert but I guess multi-labeling using this method is not very wise because network can not relate 
input features to every single label separately and therefore accuracy will be low.  Anyway, Could you find any better solution since then?
> (3) Replace the loss function with Sigmoid cross entropy or Euclidean distance loss.

Could you please elaborate how? Which part of code needs to be modified. A sample code will help a lot.

**Comment by ishann** [comment]
Another way to address this:

It should be possible to create independent annotation instances for the same object with different labels (just provide unique annotation IDs). Since the minibatch is created at the image level, the COCO API will gather all annotations (including multiple labeled ones for the same object) at the image level when feeding them to GeneralizedRCNN.

As far as learning abstractions go, it is possible to treat the different labels of the same object as completely different annotations. The only computational downside I can see is that you'll be running multiple box_pooler operations for the same GT instance to get the ROI-Pooled features. COCO has 2 orders of magnitude fewer GT compared to proposals, so you should be fine.

**Comment by information-security** [comment]
@ishann Thanks for your explanation.
I have actually tried your _independent annotation_ solution previously with Mask-RCNN and Detectron2. In case of the former, there was always just single prediction and for latter, despite very low loss values after training (which I guess means network was in a good condition), outcome was not reliable. Most of the times just one of the predictions has had acceptable score and other predictions had very low scores (Far beyond threshold). Please see [this issue](https://github.com/facebookresearch/detectron2/issues/798#issue-559322078) for more details. I've been suggested there to design a custom model for that but I have no idea to what extent I need to modify current model of Detectron2. Besides that, I think changing loss function to something like `binary_crossentropy` and setting `sigmoid` as activation for the final layer would help here. Any ideas?

**Comment by ishann** [comment]
I'm not familiar with the low-level details of maskrcnn-benchmark. For D2, outcome not being reliable depends on a host of issues that may have nothing to do with the D2 setup itself.

BCE with sigmoid activations is (theoretically) the way to go with multi-label predictions. However, in practice people usually have a hard time using BCE with sigmoid compared to softmax, especially when #classes becomes large. For example, [this paper](https://arxiv.org/abs/1805.00932) on weakly supervised learning suggests softmax is better even with multi-label data (Sec 2.3 Models).

One recent implementation where BCE+sigmoid did better than softmax was the recent LVIS Challenge [winners](https://www.lvisdataset.org/assets/challenge_reports/2019/strangeturtle_equalization_loss.pdf) (Sec. 2 Equalization Loss). You could try and see how/ why it worked for them.

**Comment by yusiyoh** [comment]
> @ishann Thanks for your explanation. I have actually tried your _independent annotation_ solution previously with Mask-RCNN and Detectron2. In case of the former, there was always just single prediction and for latter, despite very low loss values after training (which I guess means network was in a good condition), outcome was not reliable. Most of the times just one of the predictions has had acceptable score and other predictions had very low scores (Far below threshold). Please see [this issue](https://github.com/facebookresearch/detectron2/issues/798#issue-559322078) for more details. I've been suggested there to design a custom model for that but I have no idea to what extent I need to modify current model of Detectron2. Besides that, I think changing loss function to something like `binary_crossentropy` and setting `sigmoid` as activation for the final layer would help here. Any ideas?

@information-security 
Hello, could you change a detectron2 model according to what you need? I am in the same situation, and a bit lost in the codes since they are all dependent on each other. If you can share your work I will be glad. Thank you.
