### ISSUE TITLE
Import error : import pycocotools._mask as _mask, undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by MounirB** [facebookresearch/Detectron#461]
Hello everyone,

When I try to run the infer_simple.py script, I get the following error : 

`python2 tools/infer_simple.py     --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml     --output-dir /tmp/detectron-visualizations     --image-ext jpg     --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl     demo`

```
Traceback (most recent call last):
  File "tools/infer_simple.py", line 44, in <module>
    import detectron.core.test_engine as infer_engine
  File "/home/mounir/detectron/detectron/core/test_engine.py", line 35, in <module>
    from detectron.core.rpn_generator import generate_rpn_on_dataset
  File "/home/mounir/detectron/detectron/core/rpn_generator.py", line 42, in <module>
    from detectron.datasets import task_evaluation
  File "/home/mounir/detectron/detectron/datasets/task_evaluation.py", line 45, in <module>
    import detectron.datasets.cityscapes_json_dataset_evaluator \
  File "/home/mounir/detectron/detectron/datasets/cityscapes_json_dataset_evaluator.py", line 28, in <module>
    import pycocotools.mask as mask_util
  File "/home/mounir/.local/lib/python2.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: /home/mounir/.local/lib/python2.7/site-packages/pycocotools/_mask.so: undefined symbol: PyFPE_jbuf
```

### System information

* Operating system: 16.04
* Compiler version: conda 4.5.4
* CUDA version: 9.0
* cuDNN version: 7.xxx
* NVIDIA driver version: 384.130
* GPU models (for all devices if they are not all the same): Quadro P400
* `PYTHONPATH` environment variable:
```
python2 -c "import sys; print(sys.path)"
['', '/home/mounir/miniconda3/envs/newCudaPy2/lib/python27.zip', '/home/mounir/miniconda3/envs/newCudaPy2/lib/python2.7', '/home/mounir/miniconda3/envs/newCudaPy2/lib/python2.7/plat-linux2', '/home/mounir/miniconda3/envs/newCudaPy2/lib/python2.7/lib-tk', '/home/mounir/miniconda3/envs/newCudaPy2/lib/python2.7/lib-old', '/home/mounir/miniconda3/envs/newCudaPy2/lib/python2.7/lib-dynload', '/home/mounir/.local/lib/python2.7/site-packages', '/home/mounir/detectron', '/home/mounir/miniconda3/envs/newCudaPy2/lib/python2.7/site-packages', '/home/mounir/miniconda3/envs/newCudaPy2/lib/python2.7/site-packages/pycocotools-2.0-py2.7-linux-x86_64.egg', '/home/mounir/.local/lib/python2.7/site-packages', '/home/mounir/miniconda3/envs/newCudaPy2/lib/python2.7/site-packages/singledispatch-3.4.0.3-py2.7.egg']
```
* `python --version` output: Python 2.7.15 :: Anaconda, Inc.

**Comment by maozezhong** [comment]
@ir413 hello, I have the same problem. even I followed the link you provide, issue still exist

**Comment by maozezhong** [comment]
@ir413 I install caffe2 in anaconda envs, python=2.7
- the output of 'python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"' is success
- the output of 'python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'' is 1
- the output of 'python2 $DETECTRON/detectron/tests/test_spatial_narrow_as_op.py' is something like below: 
No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies.
E0618 13:47:01.160491 16431 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0618 13:47:01.160506 16431 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0618 13:47:01.160508 16431 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
...
Ran 3 tests in 0.893s
OK

---------
and in my conda envs there is only one numpy.
I still got the eror:

```
import pycocotools.mask as mask_util
  File "build/bdist.linux-x86_64/egg/pycocotools/mask.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/pycocotools/_mask.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pycocotools/_mask.py", line 6, in __bootstrap__
ImportError: /home/maozezhong/.python-eggs/pycocotools-2.0-py2.7-linux-x86_64.egg-tmp/pycocotools/_mask.so: undefined symbol: PyFPE_jbuf

```
I don't know why, hope for your reply

**Comment by maozezhong** [comment]
@MounirB do you solved the problem?

**Comment by MounirB** [comment]
@maozezhong Have you tried to remove conda's numpy and keep only pip's one ?
