### ISSUE TITLE
wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext>

### ISSUE THREAD

**Issue by LeonJWH** [facebookresearch/Detectron#505]
I tried to stack another two stage of rcnn to original maskrcnn, I added two extra python operators. I trained the cascade maskrcnn successfully and I got the final pkl model.
But when I tried to testing the final model on coco2017_test-dev, the progress broke down with the following error.
```
E0619 21:16:40.863662   569 net_dag.cc:195] Exception from operator chain starting at '' (type 'RoIAlign'): caffe2::EnforceNotMet: [enforce fail at blob.h:84] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/roi_3rd_fpn5.
Error from operator:
input: "gpu_0/fpn_res5_2_sum" input: "gpu_0/roi_3rd_fpn5" output: "gpu_0/roi_feat_3rd_fpn5" name: "" type: "RoIAlign" arg { name: "pooled_h" i: 7 } arg { name: "sampling_ratio" i: 2 } arg { name: "spatial_scale" f: 0.03125 } arg { name: "pooled_w" i: 7 } device_option { device_type: 1 cuda_gpu_id: 0 }
WARNING workspace.py: 185: Original python traceback for operator `252` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/tools/test_net.py", line 116, in <module>
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 127, in run_inference
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 124, in result_getter
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 233, in test_net
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 326, in initialize_model_from_cfg
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 124, in create
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 89, in generalized_rcnn
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 230, in build_generic_detection_model
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/modeling/optimizer.py", line 54, in build_data_parallel_model
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 204, in _single_gpu_build_func
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 273, in _add_cascade_fast_rcnn_head
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/modeling/fast_rcnn_heads.py", line 315, in add_roi_cascade_2mlp_head
WARNING workspace.py: 190:   File "/home/user/workspace/Detectron/detectron_cascade/modeling/detector.py", line 363, in RoIFeatureTransform
Traceback (most recent call last):
  File "/home/user/workspace/Detectron/tools/test_net.py", line 116, in <module>
    check_expected_results=True,
  File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 127, in run_inference
    all_results = result_getter()
  File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 124, in result_getter
    gpu_id=gpu_id
  File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 256, in test_net
    model, im, box_proposals, timers
  File "/home/user/workspace/Detectron/detectron_cascade/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/user/workspace/Detectron/detectron_cascade/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at blob.h:84] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/roi_3rd_fpn5.
Error from operator:
input: "gpu_0/fpn_res5_2_sum" input: "gpu_0/roi_3rd_fpn5" output: "gpu_0/roi_feat_3rd_fpn5" name: "" type: "RoIAlign" arg { name: "pooled_h" i: 7 } arg { name: "sampling_ratio" i: 2 } arg { name: "spatial_scale" f: 0.03125 } arg { name: "pooled_w" i: 7 } device_option { device_type: 1 cuda_gpu_id: 0 }
Traceback (most recent call last):
  File "tools/test_net.py", line 116, in <module>
    check_expected_results=True,
  File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 127, in run_inference
    all_results = result_getter()
  File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 107, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 154, in test_net_on_dataset
    weights_file, dataset_name, proposal_file, num_images, output_dir
  File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 186, in multi_gpu_test_net_on_dataset
    'detection', num_images, binary, output_dir, opts
  File "/home/user/workspace/Detectron/detectron_cascade/utils/subprocess.py", line 95, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home/user/workspace/Detectron/detectron_cascade/utils/subprocess.py", line 133, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 1)
```
Does it mean that the **roi_3rd_fpn5** is not in the blob? No error occured at rcnn stage 2.

**Comment by Seaor** [comment]
@LeonJWH  have u solved that?

**Comment by 0HaNC** [comment]
Perhaps your config file does not match the weights.
