### ISSUE TITLE
RuntimeError:  out of memory 

### ISSUE THREAD

**Issue by ningxiangyun** [facebookresearch/Detectron#560]
Traceback (most recent call last):
  File "tools/train_net.py", line 128, in <module>
    main()
  File "tools/train_net.py", line 110, in main
    checkpoints = detectron.utils.train.train_model()
  File "/home/sd/Detectron/detectron/utils/train.py", line 54, in train_model
    model, weights_file, start_iter, checkpoints, output_dir = create_model()
  File "/home/sd/Detectron/detectron/utils/train.py", line 143, in create_model
    workspace.RunNetOnce(model.param_init_net)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 199, in RunNetOnce
    StringifyProto(net),
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at event_gpu.cc:17] error == cudaSuccess. 2 vs 0. Error at: /home/sd/pytorch/caffe2/core/event_gpu.cc:17: out of memory 
It means only I need more memory?

**Comment by ir413** [comment]
Hi @ningxiangyun - yes, the error suggests that you run out of memory.
