### ISSUE TITLE
Inference with COCO datasets: AttributeError

### ISSUE THREAD

**Issue by yagee97** [facebookresearch/Detectron#571]
**I installed both caffe2 and detectron. So, I tried to test the detectron.
While test with coco datasets, an attributeError has occurred!
how I can solve it?**

 use commend line
`python2 ~/detectron/tools/test_net.py \
--cfg ~/detectron/configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
TEST.WEIGHTS https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl NUM_GPUS 1`

<hr>

the error like this:

Traceback (most recent call last):
  File "/home/adg/detectron/tools/test_net.py", line 116, in <module>
    check_expected_results=True,
  File "/home/adg/densepose/detectron/core/test_engine.py", line 120, in run_inference
    all_results = result_getter()
  File "/home/adg/densepose/detectron/core/test_engine.py", line 100, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/adg/densepose/detectron/core/test_engine.py", line 158, in test_net_on_dataset
    dataset, all_boxes, all_segms, all_keyps, all_bodys, output_dir
  File "/home/adg/densepose/detectron/datasets/task_evaluation.py", line 53, in evaluate_all
    dataset, all_boxes, output_dir, use_matlab=use_matlab
  File "/home/adg/densepose/detectron/datasets/task_evaluation.py", line 77, in evaluate_boxes
    dataset, all_boxes, output_dir, use_salt=not_comp, cleanup=not_comp
  File "/home/adg/densepose/detectron/datasets/json_dataset_evaluator.py", line 133, in evaluate_boxes
    coco_eval = _do_detection_eval(json_dataset, res_file, output_dir)
  File "/home/adg/densepose/detectron/datasets/json_dataset_evaluator.py", line 189, in _do_detection_eval
    coco_eval.evaluate()
  File "/home/adg/densepose/detectron/datasets/densepose_cocoeval.py", line 252, in evaluate
    self._prepare()
  File "/home/adg/densepose/detectron/datasets/densepose_cocoeval.py", line 227, in _prepare
    if _checkIgnore(dt, self._igrgns[dt['image_id']]):
  File "/home/adg/densepose/detectron/datasets/densepose_cocoeval.py", line 166, in _checkIgnore
    x2 = min([x2,iregion.shape[1]])
AttributeError: 'list' object has no attribute 'shape'

### System information

* Operating system: Ubuntu 16.04
* CUDA version: 8.0
* cuDNN version: 6.0
* NVIDIA driver version: 384.130
* `PYTHONPATH` environment variable: /home/adg/pytorch/build:$PYTHONPATH
* `python --version` output: 2.7.12

**Comment by ir413** [comment]
Hi @yagee97, looking at the stack trace  it seems that your detectron and densepose packages/modules are getting mixed (e.g. `densepose/detectron/datasets/densepose_cocoeval.py`). The easiest way to resolve this and run detectron successfully would be to run `make clean` from your densepose repo followed by `make` from your detectron repo. Sorry for the inconvenience.

**Comment by yagee97** [comment]
Thank you for your reply! i will try to your method
