### ISSUE TITLE
yaml.constructor.ConstructorError: while constructing a Python object > cannot find module 'detectron.utils.collections'

### ISSUE THREAD

**Issue by miriam124578** [facebookresearch/Detectron#575]
When running infer_simple I get an error related to yaml:

> yaml.constructor.ConstructorError: while constructing a Python object
> cannot find module 'detectron.utils.collections' (No module named detectron.utils.collections)
>   in "<string>", line 9, column 12:
>       CLUSTER: !!python/object/new:detectron.ut ... 

Here is the full error:

> 
> xxxxx@xxxxxxxxxxxxxxxxxxxxx:~/projects/detectron$ python2 tools/infer_simple.py \
> >     --cfg /home/local/ANT/xxxxx/projects/detectron/configs/12_2017_baselines/e2e_mask_rcnn_X-152-32x8d-FPN-IN5k_1.44x.yaml \
> >     --output-dir /tmp/output \
> >     --image-ext jpg \
> >     --wts /home/local/ANT/xxxxx/projects/detectron/model_final.pkl \
> >     --im_or_folder /testset
> Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
> E0718 18:30:56.599776  6995 init_intrinsics_check.cc:59] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
> E0718 18:30:56.599794  6995 init_intrinsics_check.cc:59] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
> E0718 18:30:56.599813  6995 init_intrinsics_check.cc:59] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
> WARNING cnn.py:  40: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
> INFO net.py:  57: Loading weights from: /home/local/ANT/xxxxx/projects/detectron/model_final.pkl
> Traceback (most recent call last):
>   File "tools/infer_simple.py", line 152, in <module>
>     main(args)
>   File "tools/infer_simple.py", line 104, in main
>     model = infer_engine.initialize_model_from_cfg(args.weights)
>   File "/home/local/ANT/xxxxx/projects/detectron/lib/core/test_engine.py", line 316, in initialize_model_from_cfg
>     model, weights_file, gpu_id=gpu_id,
>   File "/home/local/ANT/xxxxxx/projects/detectron/lib/utils/net.py", line 62, in initialize_gpu_from_weights_file
>     saved_cfg = yaml.load(src_blobs['cfg'])
>   File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
>     return loader.get_single_data()
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 39, in get_single_data
>     return self.construct_document(node)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 43, in construct_document
>     data = self.construct_object(node)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
>     data = constructor(self, tag_suffix, node)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 610, in construct_python_object_new
>     return self.construct_python_object_apply(suffix, node, newobj=True)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 593, in construct_python_object_apply
>     value = self.construct_mapping(node, deep=True)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
>     return BaseConstructor.construct_mapping(self, node, deep=deep)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 133, in construct_mapping
>     value = self.construct_object(value_node, deep=deep)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 95, in construct_object
>     for dummy in generator:
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 398, in construct_yaml_map
>     value = self.construct_mapping(node)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
>     return BaseConstructor.construct_mapping(self, node, deep=deep)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 133, in construct_mapping
>     value = self.construct_object(value_node, deep=deep)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
>     data = constructor(self, tag_suffix, node)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 610, in construct_python_object_new
>     return self.construct_python_object_apply(suffix, node, newobj=True)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 599, in construct_python_object_apply
>     instance = self.make_python_instance(suffix, node, args, kwds, newobj)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 540, in make_python_instance
>     cls = self.find_python_name(suffix, node.start_mark)
>   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 508, in find_python_name
>     "cannot find module %r (%s)" % (module_name.encode('utf-8'), exc), mark)
> yaml.constructor.ConstructorError: while constructing a Python object
> cannot find module 'detectron.utils.collections' (No module named detectron.utils.collections)
>   in "<string>", line 9, column 12:
>       CLUSTER: !!python/object/new:detectron.ut ... 

This is similar to the error reported here: https://github.com/facebookresearch/DensePose/issues/37
The suggested solution (using PyYAML version 3.12 instead of 4.1) doesn't work for me, as I already have version 3.12 installed.

* Operating system: Linux
* Compiler version: gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~16.04) 
* CUDA version: 8.0.61
* cuDNN version: 6
* NVIDIA driver version: 396.37
* GPU models (for all devices if they are not all the same): Titan Xp
* `python --version` output: 2.7

**Comment by ir413** [comment]
Hi @miriam124578, looking at the stack trace (e.g. `lib/core/test_engine.py`) it seems that you're using an older version of Detectron (before e5bb3a8). However, it is weird that your config parser is still trying to retrieve `detectron.utils.collections` (this should only happen after e5bb3a8). This may suggest that your python packages are getting mixed in some way. Could you please try to reproduce this using a fresh clone of the latest detectron? It may also be worth trying `make clean` followed by `make` in your current version.

**Comment by lssily** [comment]
@ir413 Hi! I encountered the same question as @miriam124578. Is there other solution for this problem without updating the version of Detectron?
