### ISSUE TITLE
Multiple Threads Error

### ISSUE THREAD

**Issue by fire17** [facebookresearch/Detectron#619]
Hi there,
when I run Detectron simultaneously on 2 pictures in different threads I get: 

```
E0815 15:12:52.194861 13270 net_async_scheduling.cc:213] Detected concurrent runs
E0815 15:12:52.194883 13270 net.h:57] Failed to execute async run
WARNING workspace.py: 185: Original python traceback for operator `-205365160` in network `generalized_rcnn` in exception above (most recent call last):
Unhandled exception in thread started by <function RunDetectronThread at 0x7f6196e9d9b0>
Traceback (most recent call last):
  File "/home/user/Detectron/tools/webcams_depth.py", line 321, in RunDetectronThread
    DetData[0] = RunDetectron(DetData[2],DetData[3],DetData[4],DetData[5],DetData[6],DetData[7],DetData[8])
  File "/home/user/Detectron/tools/webcams_depth.py", line 333, in RunDetectron
    model, im, None, timers=timers
  File "/home/user/Detectron/detectron/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/user/Detectron/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/home/user/pytorch/build/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/user/pytorch/build/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1059] success. Error running net generalized_rcnn
``` 

I wish to run more inferences faster, so either make 1 instance faster or create multiple simultaneous runs...
Any thoughts?
Thank you very much!
Tami

**Comment by ir413** [comment]
Hi @fire17, it is hard to say much about the error without seeing to the code you're using.
