### ISSUE TITLE
detectron issue ( test_spatial_narrow_as_op.py error)

### ISSUE THREAD

**Issue by PuyaYavari** [facebookresearch/Detectron#634]
I am working on a project and I need to use DensePose model.
I tried to install DensePose on an Amazon EC2 P3.8xlarge. Since it's an Amazon instance I am sure about the CUDA and cudnn installations.
I followed the official installation instructions (https://github.com/facebookresearch/DensePose/blob/master/INSTALL.md). Caffe2 is ok and Caffe2 installation is verified. But the detectron test fails everytime and no matter what I tried it always fails.
I did set the PYTHONPATH and it didn't change anything.
I also uninstalled and reinstalled Caffe2 many times and many ways and it didn't work too.

I have tried all of these and no result:
https://github.com/facebookresearch/Detectron/issues/260
https://github.com/facebookresearch/Detectron/issues/502
https://github.com/facebookresearch/Detectron/issues/549

ERROR:

.../DensePose/detectron/tests$ python test_spatial_narrow_as_op.py 
E0823 21:24:10.062685 104626 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0823 21:24:10.062728 104626 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0823 21:24:10.062733 104626 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
Traceback (most recent call last):
  File "test_spatial_narrow_as_op.py", line 80, in <module>
    c2_utils.import_detectron_ops()
  File "/home/ubuntu/Cabin/HazirModel/DensePose/detectron/utils/c2.py", line 34, in import_detectron_ops
    dyndep.InitOpsLibrary(detectron_ops_lib)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/home/ubuntu/anaconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZTVN6caffe213EnforceNotMetE

### System information

* Operating system: Ubuntu 16.04
* CUDA version: CUDA 9
* cuDNN version: 7.1.2
* NVIDIA driver version: 
* GPU models (for all devices if they are not all the same): 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1B.0 Off |                    0 |
| N/A   37C    P0    25W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:1C.0 Off |                    0 |
| N/A   36C    P0    25W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:1D.0 Off |                    0 |
| N/A   35C    P0    24W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   37C    P0    25W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
* `PYTHONPATH` environment variable: tried multiple
* `python --version` output: Python 2.7.15 :: Anaconda, Inc.
* Anything else that seems relevant: I also tried instances ready caffe2 environment and also created a new environment and tried everything there and still had the problem. The only thing that I think could cause the problem is the usage of sudo I had to run some commands with sudo and as I know that can cause some problems in PATH.
Also I have some problem with PYTHONPATH which I guess I know why it is happening but everytime I restart the instance it is cleared.

**Comment by jiangguoding** [comment]
I can not run detectron after trying many ways.
Now I am reading the https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md

could it be possible version uncompatible with CUDA 9.0 ????
 this is the note: 
    Detectron operators currently do not have CPU implementation; a GPU system is required.
    Detectron has been tested extensively with CUDA 8.0 and cuDNN 6.0.21.

Waiting for somebody reply...

**Comment by gadcam** [comment]
@PuyaYavari #202 & #428 seem linked to your issue.
Looks like it does not find the Detectron ops.

**Comment by MuhammadAsadJaved** [comment]
@PuyaYavari  did you resolve your problem? i also have same problem. Hoe you change the PYTHONPATH?
