### ISSUE TITLE
i have compiled detectron,but test detectron meet a error,and i have do anything i can do and i don't know how to solve it

### ISSUE THREAD

**Issue by zhangchao110** [facebookresearch/Detectron#658]
ubuntu@ubuntu-MS-7A94:~$ python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Success

ubuntu@ubuntu-MS-7A94:~/detectron$ make
python2 setup.py develop --user
running develop
running egg_info
writing Detectron.egg-info/PKG-INFO
writing top-level names to Detectron.egg-info/top_level.txt
writing dependency_links to Detectron.egg-info/dependency_links.txt
reading manifest file 'Detectron.egg-info/SOURCES.txt'
writing manifest file 'Detectron.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/detectron/utils/cython_bbox.so -> detectron/utils
copying build/lib.linux-x86_64-2.7/detectron/utils/cython_nms.so -> detectron/utils
Creating /home/ubuntu/.local/lib/python2.7/site-packages/Detectron.egg-link (link to .)
Detectron 0.0.0 is already the active version in easy-install.pth
Installed /home/ubuntu/detectron
Processing dependencies for Detectron==0.0.0
Finished processing dependencies for Detectron==0.0.0

buntu@ubuntu-MS-7A94:~$ python2 detectron/detectron/tests/test_spatial_narrow_as_op.py
No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies.
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
Traceback (most recent call last):
  File "detectron/detectron/tests/test_spatial_narrow_as_op.py", line 88, in <module>
    c2_utils.import_detectron_ops()
  File "/home/ubuntu/detectron/detectron/utils/c2.py", line 44, in import_detectron_ops
    dyndep.InitOpsLibrary(detectron_ops_lib)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.9.0: cannot open shared object file: No such file or directory

**Comment by gadcam** [comment]
This issue is about this problem https://github.com/caffe2/caffe2/issues/2212

**Comment by zhangchao110** [comment]
> This issue is about this problem [caffe2/caffe2#2212](https://github.com/caffe2/caffe2/issues/2212)

thanks for your answers,i have studied the discussion and i didn't find right answers.i plan to reinstall cuda,caffe2 and detectron
