### ISSUE TITLE
when I train coco2014 dataset,I get an error,how to solve it?

### ISSUE THREAD

**Issue by gittigxuy** [facebookresearch/Detectron#662]
python2 tools/train_net.py --cfg configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml OUTPUT_DIR /tmp/detectron-output

I get the following error:

Traceback (most recent call last):
File "tools/train_net.py", line 132, in
main()
File "tools/train_net.py", line 114, in main
checkpoints = detectron.utils.train.train_model()
File "/home/test/detectron/detectron/utils/train.py", line 53, in train_model
model, weights_file, start_iter, checkpoints, output_dir = create_model()
File "/home/test/detectron/detectron/utils/train.py", line 149, in create_model
workspace.RunNetOnce(model.param_init_net)
File "/home/test/pytorch/build/caffe2/python/workspace.py", line 201, in RunNetOnce
StringifyProto(net),
File "/home/test/pytorch/build/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
return func(*args, **kwargs)
RuntimeError: [enforce fail at math_gpu.cu:1586] status == CURAND_STATUS_SUCCESS. 102 vs 0. Error at: /home/test/pytorch/caffe2/utils/math_gpu.cu:1586: CURAND_STATUS_ALLOCATION_FAILEDError from operator:
output: "gpu_0/res5_2_branch2a_w" name: "" type: "XavierFill" arg { name: "shape" ints: 512 ints: 2048 ints: 1 ints: 1 } device_option { device_type: 1 cuda_gpu_id: 0 }

I just change the train weights to my local path in the tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml file

TRAIN:
  WEIGHTS: /home/test/caffe2_model/R-50/R-50.pkl
  DATASETS: ('coco_2014_train',)
  SCALES: (500,)
  MAX_SIZE: 833
  BATCH_SIZE_PER_IM: 256
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level

how could I solve the problem?

**Comment by MarcusNerva** [comment]
@gittigxuy Hi there! Did you solve this problem? I meet this problem too!
