### ISSUE TITLE
When I use cityscapes2coco.py,I meet following error

### ISSUE THREAD

**Issue by gittigxuy** [facebookresearch/Detectron#691]
Processed 0 images, 0 annotations
Traceback (most recent call last):
File "tools/convert_cityscapes_to_coco_bddFormat.py", line 212, in
convert_cityscapes_instance_only(datadir, outdir)
File "tools/convert_cityscapes_to_coco_bddFormat.py", line 168, in convert_cityscapes_instance_only
if obj['contours'] == []:
KeyError: u'contours'

when I try print (obj.keys())
and the result is :
['medDist', 'instID', 'distConf', 'labelID', 'pixelCount']
it does not have contours

I download gtFine_trainvaltest.zip (241MB) [md5] and leftImg8bit_trainvaltest.zip (11GB) [md5]

how could I solve the error?

**Comment by kHarshit** [comment]
It might help you https://github.com/facebookresearch/Detectron/issues/111#issuecomment-363425465
