### ISSUE TITLE
Can I train Keypoint RCNN without FPN? I got a shape error~!

### ISSUE THREAD

**Issue by dedoogong** [facebookresearch/Detectron#702]
I modified e2e_keypoint_rcnn_R-50-FPN_s1x.yaml as below;
```
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet50_conv4_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  KEYPOINTS_ON: True
NUM_GPUS: 2
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 130000
  STEPS: [0, 100000, 120000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
KRCNN:
  ROI_KEYPOINTS_HEAD: keypoint_rcnn_heads.add_ResNet_roi_conv5_head_for_keypoints
  NUM_STACKED_CONVS: 8
  NUM_KEYPOINTS: 17
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56  # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  KEYPOINT_CONFIDENCE: bbox
  DILATION: 1
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('keypoints_coco_2014_train', 'keypoints_coco_2014_valminusminival')
  SCALES: (640, 672, 704, 736, 768, 800)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000   
TEST:
  WEIGHTS: /home/lee/detectron/model_final.pkl
  DATASETS: ('keypoints_coco_2014_minival',)
  SCALE: 800 #224
  MAX_SIZE: 1333 #224
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000   
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .
```
and when I run training with a normal command like 
"python3 tools/train_net.py --cfg configs/12_2017_baselines/e2e_keypoint_rcnn_R-50-FPN_s1x.yaml OUTPUT_DIR /home/detectron/detectron-output", 

I got errors:
```
Traceback (most recent call last):
  File "tools/train_net.py", line 128, in <module>
    main()
  File "tools/train_net.py", line 110, in main
    checkpoints = detectron.utils.train.train_model()
  File "/home/lee/detectron/detectron/utils/train.py", line 66, in train_model
    workspace.RunNet(model.net.Proto().name)
  File "/home/lee/caffe2-pytorch/build/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/lee/caffe2-pytorch/build/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at reshape_op.h:99] total_size % size == 0. Argument `shape` does not agree with the input data. (**39984 vs 3136) Error from operator: 
input: "gpu_1/kps_score" output: "gpu_1/kps_score_reshaped" output: "gpu_1/_kps_score_old_shape" name: "" type: "Reshape" arg { name: "shape" ints: -1 ints: 3136 } device_option { device_type: 1 cuda_gpu_id: 1 }
^CINFO loader.py: 294: SIGINT: Shutting down RoIDataLoader threads and exiting...
```
kps_score is the output of the last deconv layer, so its shape should be like (1,17,56,56 = 53312)
but, 39984 = 7 x 7 x 8 x 51 x 2  and
3136 is 64 x 7 x 7...

and if I remove 2 lines 
  **ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2**

I got a similar shape error : 
```
E1011 17:24:59.301152  3106 net_async_base.cc:368] [enforce fail at reshape_op.h:99] total_size % size == 0. Argument `shape` does not agree with the input data. (**199920 vs 3136) Error from operator: 
input: "gpu_1/kps_score" output: "gpu_1/kps_score_reshaped" output: "gpu_1/_kps_score_old_shape" name: "" type: "Reshape" arg { name: "shape" ints: -1 ints: 3136 } device_option { device_type: 1 cuda_gpu_id: 1 },  op Reshape
WARNING workspace.py: 187: Original python traceback for operator `469` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 192:   File "tools/train_net.py", line 128, in <module>
WARNING workspace.py: 192:   File "tools/train_net.py", line 110, in main
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/utils/train.py", line 54, in train_model
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/utils/train.py", line 139, in create_model
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/modeling/model_builder.py", line 124, in create
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/modeling/model_builder.py", line 89, in generalized_rcnn
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/modeling/model_builder.py", line 236, in build_generic_detection_model
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/modeling/optimizer.py", line 40, in build_data_parallel_model
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/modeling/optimizer.py", line 63, in _build_forward_graph
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/modeling/model_builder.py", line 224, in _single_gpu_build_func
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/modeling/model_builder.py", line 327, in _add_roi_keypoint_head
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/modeling/keypoint_rcnn_heads.py", line 147, in add_keypoint_losses
WARNING workspace.py: 192:   File "/home/lee/detectron/detectron/utils/blob.py", line 170, in get_loss_gradients
Traceback (most recent call last):
  File "tools/train_net.py", line 128, in <module>
    main()
  File "tools/train_net.py", line 110, in main
    checkpoints = detectron.utils.train.train_model()
  File "/home/lee/detectron/detectron/utils/train.py", line 66, in train_model
    workspace.RunNet(model.net.Proto().name)
  File "/home/lee/caffe2-pytorch/build/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/lee/caffe2-pytorch/build/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at reshape_op.h:99] total_size % size == 0. Argument `shape` does not agree with the input data. (**199920 vs 3136**) Error from operator: 
input: "gpu_1/kps_score" output: "gpu_1/kps_score_reshaped" output: "gpu_1/_kps_score_old_shape" name: "" type: "Reshape" arg { name: "shape" ints: -1 ints: 3136 } device_option { device_type: 1 cuda_gpu_id: 1 }
```

And when I delete RPN part in the yaml,
RPN:  
   SIZES: (32, 64, 128, 256, 512)

I passed the shape error in key_score reshape operator but faced another error in softmax :
....softmax_ops.cu:306] T.size_to_dim(canonical_axis) == N. 544 vs 136 Error from operator:
136=4*2*17, but key_score outputs 4*17 per each roi when I refer the keypoints.py
            xy_preds[i, 0, k] = x + offset_x[i]
            xy_preds[i, 1, k] = y + offset_y[i]
            xy_preds[i, 2, k] = roi_map[k, y_int, x_int]
            xy_preds[i, 3, k] = roi_map_probs[k, y_int, x_int] # k is in [0,17] and i is in range(len(rois))

544 = 4*136. 
Hum... 
I can't guess why this kind of shape is produced. 

Is there any body who tried training Keypoint RCNN without FPN ?

Please help me~!

Thank you in advance.

**Comment by dedoogong** [comment]
I solved this issue ;) I made a mistake in the yaml file.
