### ISSUE TITLE
Training Fail (train_net.py)

### ISSUE THREAD

**Issue by shadowdk3** [facebookresearch/Detectron#713]
I follow `GETTING_STARTED.md` instruction, I got `infer_simple.py` and run an end-to-end trained Mask R-CNN model is OK. But when I try to run training, it fails.

training cmd:
```
python tools/train_net.py \
    --multi-gpu-testing \
    --cfg configs/getting_started/tutorial_2gpu_e2e_faster_rcnn_R-50-FPN.yaml \
    OUTPUT_DIR /tmp/detectron-output
```
I have already try to use single GPU and multi GPU, it still have same error.
 
I got the error after trainning:

```
 'USE_NCCL': False,
 'VIS': False,
 'VIS_TH': 0.9}
loading annotations into memory...
Done (t=0.67s)
creating index...
index created!
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  57: Loading weights from: /tmp/detectron-output/train/coco_2014_train/generalized_rcnn/model_final.pkl
INFO net.py:  91: cls_score_w not found
INFO net.py:  91: cls_score_b not found
I1018 15:45:24.951298 22348 operator.cc:195] Engine CUDNN is not available for operator MaxPool.
I1018 15:45:24.956285 22348 operator.cc:195] Engine CUDNN is not available for operator MaxPool.
I1018 15:45:24.958238 22348 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 8.5932e-05 secs
I1018 15:45:24.960499 22348 operator.cc:195] Engine CUDNN is not available for operator MaxPool.
I1018 15:45:24.965612 22348 operator.cc:195] Engine CUDNN is not available for operator MaxPool.
I1018 15:45:24.965818 22348 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 7.0936e-05 secs
I1018 15:45:26.046360 22348 net_async_base.h:198] Using specified CPU pool size: 4; NUMA node id: -1
I1018 15:45:26.046391 22348 net_async_base.h:203] Created new CPU pool, size: 4; NUMA node id: -1
E1018 15:45:27.075666 22442 net_async_base.cc:422] IsType<T>() ASSERT FAILED at /home/user/pytorch/aten/src/ATen/core/blob.h:79, please report a bug to PyTorch. wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor.
Offending Blob name: gpu_0/cls_score_cs_w.
Error from operator:
input: "gpu_0/fc7" input: "gpu_0/cls_score_cs_w" input: "gpu_0/cls_score_cs_b" output: "gpu_0/cls_score_cs" name: "" type: "FC" arg { name: "use_cudnn" i: 1 } arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 device_id: 0 } (Get at /home/user/pytorch/aten/src/ATen/core/blob.h:79)
frame #0: <unknown function> + 0x108747e (0x7fb25ebe647e in /usr/local/lib/libcaffe2_gpu.so)
frame #1: caffe2::FullyConnectedOp<caffe2::CUDAContext, caffe2::DefaultEngine, true>::RunOnDevice() + 0x108 (0x7fb25ebe0818 in /usr/local/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0xf6c915 (0x7fb25eacb915 in /usr/local/lib/libcaffe2_gpu.so)
frame #3: caffe2::AsyncNetBase::run(int, int) + 0x154 (0x7fb297fcb8a4 in /usr/local/lib/libcaffe2.so)
frame #4: <unknown function> + 0x122c1a7 (0x7fb297fda1a7 in /usr/local/lib/libcaffe2.so)
frame #5: <unknown function> + 0x1221ce3 (0x7fb297fcfce3 in /usr/local/lib/libcaffe2.so)
frame #6: <unknown function> + 0xb8c80 (0x7fb31713ac80 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #7: <unknown function> + 0x76ba (0x7fb31fc186ba in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x6d (0x7fb31f94e41d in /lib/x86_64-linux-gnu/libc.so.6)
,  op FC
WARNING workspace.py: 187: Original python traceback for operator `229` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 192:   File "/home/user/detectron/tools/test_net.py", line 130, in <module>
WARNING workspace.py: 192:   File "/home/user/detectron/tools/test_net.py", line 98, in main
WARNING workspace.py: 192:   File "/home/user/detectron/lib/core/test_engine.py", line 122, in run_inference
WARNING workspace.py: 192:   File "/home/user/detectron/lib/core/test_engine.py", line 221, in test_net
WARNING workspace.py: 192:   File "/home/user/detectron/lib/core/test_engine.py", line 314, in initialize_model_from_cfg
WARNING workspace.py: 192:   File "/home/user/detectron/lib/modeling/model_builder.py", line 124, in create
WARNING workspace.py: 192:   File "/home/user/detectron/lib/modeling/model_builder.py", line 89, in generalized_rcnn
WARNING workspace.py: 192:   File "/home/user/detectron/lib/modeling/model_builder.py", line 229, in build_generic_detection_model
WARNING workspace.py: 192:   File "/home/user/detectron/lib/modeling/optimizer.py", line 54, in build_data_parallel_model
WARNING workspace.py: 192:   File "/home/user/detectron/lib/modeling/model_builder.py", line 203, in _single_gpu_build_func
WARNING workspace.py: 192:   File "/home/user/detectron/lib/modeling/model_builder.py", line 256, in _add_fast_rcnn_head
WARNING workspace.py: 192:   File "/home/user/detectron/lib/modeling/fast_rcnn_heads.py", line 53, in add_fast_rcnn_outputs
WARNING workspace.py: 192:   File "/usr/local/lib/python2.7/site-packages/caffe2/python/cnn.py", line 134, in FC
WARNING workspace.py: 192:   File "/usr/local/lib/python2.7/site-packages/caffe2/python/brew.py", line 107, in scope_wrapper
WARNING workspace.py: 192:   File "/usr/local/lib/python2.7/site-packages/caffe2/python/helpers/fc.py", line 58, in fc
WARNING workspace.py: 192:   File "/usr/local/lib/python2.7/site-packages/caffe2/python/helpers/fc.py", line 54, in _FC_or_packed_FC
Traceback (most recent call last):
  File "/home/user/detectron/tools/test_net.py", line 130, in <module>
    multi_gpu_testing=args.multi_gpu_testing
  File "/home/user/detectron/tools/test_net.py", line 98, in main
    multi_gpu_testing=multi_gpu_testing,
  File "/home/user/detectron/lib/core/test_engine.py", line 122, in run_inference
    gpu_id=gpu_id
  File "/home/user/detectron/lib/core/test_engine.py", line 244, in test_net
    model, im, box_proposals, timers
  File "/home/user/detectron/lib/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/user/detectron/lib/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/usr/local/lib/python2.7/site-packages/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/site-packages/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: IsType<T>() ASSERT FAILED at /home/user/pytorch/aten/src/ATen/core/blob.h:79, please report a bug to PyTorch. wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor.
Offending Blob name: gpu_0/cls_score_cs_w.
Error from operator:
input: "gpu_0/fc7" input: "gpu_0/cls_score_cs_w" input: "gpu_0/cls_score_cs_b" output: "gpu_0/cls_score_cs" name: "" type: "FC" arg { name: "use_cudnn" i: 1 } arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 device_id: 0 } (Get at /home/user/pytorch/aten/src/ATen/core/blob.h:79)
frame #0: <unknown function> + 0x108747e (0x7fb25ebe647e in /usr/local/lib/libcaffe2_gpu.so)
frame #1: caffe2::FullyConnectedOp<caffe2::CUDAContext, caffe2::DefaultEngine, true>::RunOnDevice() + 0x108 (0x7fb25ebe0818 in /usr/local/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0xf6c915 (0x7fb25eacb915 in /usr/local/lib/libcaffe2_gpu.so)
frame #3: caffe2::AsyncNetBase::run(int, int) + 0x154 (0x7fb297fcb8a4 in /usr/local/lib/libcaffe2.so)
frame #4: <unknown function> + 0x122c1a7 (0x7fb297fda1a7 in /usr/local/lib/libcaffe2.so)
frame #5: <unknown function> + 0x1221ce3 (0x7fb297fcfce3 in /usr/local/lib/libcaffe2.so)
frame #6: <unknown function> + 0xb8c80 (0x7fb31713ac80 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #7: <unknown function> + 0x76ba (0x7fb31fc186ba in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x6d (0x7fb31f94e41d in /lib/x86_64-linux-gnu/libc.so.6)

Traceback (most recent call last):
  File "tools/train_net.py", line 280, in <module>
    main()
  File "tools/train_net.py", line 122, in main
    test_model(checkpoints['final'], args.multi_gpu_testing, args.opts)
  File "tools/train_net.py", line 276, in test_model
    test_net.main(model_file, multi_gpu_testing=multi_gpu_testing)
  File "/home/user/detectron/tools/test_net.py", line 98, in main
    multi_gpu_testing=multi_gpu_testing,
  File "/home/user/detectron/lib/core/test_engine.py", line 105, in run_inference
    multi_gpu=multi_gpu_testing
  File "/home/user/detectron/lib/core/test_engine.py", line 141, in test_net_on_dataset
    weights_file, dataset_name, proposal_file, num_images, output_dir
  File "/home/user/detectron/lib/core/test_engine.py", line 174, in multi_gpu_test_net_on_dataset
    'detection', num_images, binary, output_dir, opts
  File "/home/user/detectron/lib/utils/subprocess.py", line 95, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home/user/detectron/lib/utils/subprocess.py", line 133, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 1)
```

### System information

* Operating system:  Ubuntu 16.04
* Compiler version: ?
* CUDA version: 8.0.61
* cuDNN version: 6.0.21
* NVIDIA: GTX1080 * 4
* `python --version` output: ? python2

**Comment by ir413** [comment]
Hi @shadowdk3, it looks like you made some modifications to the code? It seems that the blob `cls_score_cs` you are trying to use is not initialized. Please ensure that all the blobs your operators require are present in the workspace when the operators are run.

**Comment by anguoyang** [comment]
@ir413 I have the same problem, never change the code, please help, thank you

**Comment by ciwei123** [comment]
@ir413 @anguoyang Do  you solved the problem? Could you share me with the method? Thank you very much!!
