### ISSUE TITLE
Error in distrubuted training

### ISSUE THREAD

**Issue by mingruimingrui** [facebookresearch/Detectron#714]
Hi, I got this error when training maskrcnn on 2 gpus

```
[E pybind_state.h:432] Exception encountered running PythonOp function: ValueError: min() arg is an empty sequence

At:
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/utils/segms.py(136): polys_to_boxes
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/roi_data/mask_rcnn.py(46): add_mask_rcnn_blobs
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/roi_data/fast_rcnn.py(197): _sample_rois
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/roi_data/fast_rcnn.py(112): add_fast_rcnn_blobs
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/ops/collect_and_distribute_fpn_rpn_proposals.py(62): forward

[E net_async_base.cc:422] [enforce fail at pybind_state.h:433] . Exception encountered running PythonOp function: ValueError: min() arg is an empty sequence

At:
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/utils/segms.py(136): polys_to_boxes
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/roi_data/mask_rcnn.py(46): add_mask_rcnn_blobs
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/roi_data/fast_rcnn.py(197): _sample_rois
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/roi_data/fast_rcnn.py(112): add_fast_rcnn_blobs
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/ops/collect_and_distribute_fpn_rpn_proposals.py(62): forward
Error from operator:
input: "gpu_1/rpn_rois_fpn2" input: "gpu_1/rpn_rois_fpn3" input: "gpu_1/rpn_rois_fpn4" input: "gpu_1/rpn_rois_fpn5" input: "gpu_1/rpn_rois_fpn6" input: "gpu_1/rpn_roi_probs_fpn2" input: "gpu_1/rpn_roi_probs_fpn3" input: "gpu_1/rpn_roi_probs_fpn4" input: "gpu_1/rpn_roi_probs_fpn5" input: "gpu_1/rpn_roi_probs_fpn6" input: "gpu_1/roidb" input: "gpu_1/im_info" output: "gpu_1/rois" output: "gpu_1/labels_int32" output: "gpu_1/bbox_targets" output: "gpu_1/bbox_inside_weights" output: "gpu_1/bbox_outside_weights" output: "gpu_1/mask_rois" output: "gpu_1/roi_has_mask_int32" output: "gpu_1/masks_int32" output: "gpu_1/rois_fpn2" output: "gpu_1/rois_fpn3" output: "gpu_1/rois_fpn4" output: "gpu_1/rois_fpn5" output: "gpu_1/rois_idx_restore_int32" output: "gpu_1/mask_rois_fpn2" output: "gpu_1/mask_rois_fpn3" output: "gpu_1/mask_rois_fpn4" output: "gpu_1/mask_rois_fpn5" output: "gpu_1/mask_rois_idx_restore_int32" name: "CollectAndDistributeFpnRpnProposalsOp:gpu_1/rpn_rois_fpn2,gpu_1/rpn_rois_fpn3,gpu_1/rpn_rois_fpn4,gpu_1/rpn_rois_fpn5,gpu_1/rpn_rois_fpn6,gpu_1/rpn_roi_probs_fpn2,gpu_1/rpn_roi_probs_fpn3,gpu_1/rpn_roi_probs_fpn4,gpu_1/rpn_roi_probs_fpn5,gpu_1/rpn_roi_probs_fpn6,gpu_1/roidb,gpu_1/im_info" type: "Python" arg { name: "token" s: "forward:11" } arg { name: "grad_input_indices" } arg { name: "grad_output_indices" } device_option { device_type: 0 }Error from operator:
input: "gpu_1/rpn_rois_fpn2" input: "gpu_1/rpn_rois_fpn3" input: "gpu_1/rpn_rois_fpn4" input: "gpu_1/rpn_rois_fpn5" input: "gpu_1/rpn_rois_fpn6" input: "gpu_1/rpn_roi_probs_fpn2" input: "gpu_1/rpn_roi_probs_fpn3" input: "gpu_1/rpn_roi_probs_fpn4" input: "gpu_1/rpn_roi_probs_fpn5" input: "gpu_1/rpn_roi_probs_fpn6" input: "gpu_1/roidb" input: "gpu_1/im_info" output: "gpu_1/rois" output: "gpu_1/labels_int32" output: "gpu_1/bbox_targets" output: "gpu_1/bbox_inside_weights" output: "gpu_1/bbox_outside_weights" output: "gpu_1/mask_rois" output: "gpu_1/roi_has_mask_int32" output: "gpu_1/masks_int32" output: "gpu_1/rois_fpn2" output: "gpu_1/rois_fpn3" output: "gpu_1/rois_fpn4" output: "gpu_1/rois_fpn5" output: "gpu_1/rois_idx_restore_int32" output: "gpu_1/mask_rois_fpn2" output: "gpu_1/mask_rois_fpn3" output: "gpu_1/mask_rois_fpn4" output: "gpu_1/mask_rois_fpn5" output: "gpu_1/mask_rois_idx_restore_int32" name: "CollectAndDistributeFpnRpnProposalsOp:gpu_1/rpn_rois_fpn2,gpu_1/rpn_rois_fpn3,gpu_1/rpn_rois_fpn4,gpu_1/rpn_rois_fpn5,gpu_1/rpn_rois_fpn6,gpu_1/rpn_roi_probs_fpn2,gpu_1/rpn_roi_probs_fpn3,gpu_1/rpn_roi_probs_fpn4,gpu_1/rpn_roi_probs_fpn5,gpu_1/rpn_roi_probs_fpn6,gpu_1/roidb,gpu_1/im_info" type: "Python" arg { name: "token" s: "forward:11" } arg { name: "grad_input_indices" } arg { name: "grad_output_indices" } device_option { device_type: 1 device_id: 1 },  op Python
WARNING workspace.py: 187: Original python traceback for operator `545` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 192:   File "./tools/train_net.py", line 132, in <module>
WARNING workspace.py: 192:   File "./tools/train_net.py", line 114, in main
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/utils/train.py", line 53, in train_model
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/utils/train.py", line 145, in create_model
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/modeling/model_builder.py", line 124, in create
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/modeling/model_builder.py", line 89, in generalized_rcnn
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/modeling/model_builder.py", line 229, in build_generic_detection_model
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/modeling/optimizer.py", line 40, in build_data_parallel_model
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/modeling/optimizer.py", line 63, in _build_forward_graph
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/modeling/model_builder.py", line 189, in _single_gpu_build_func
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/modeling/rpn_heads.py", line 46, in add_generic_rpn_outputs
WARNING workspace.py: 192:   File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/modeling/FPN.py", line 457, in add_fpn_rpn_losses
Traceback (most recent call last):
  File "./tools/train_net.py", line 132, in <module>
    main()
  File "./tools/train_net.py", line 114, in main
    checkpoints = detectron.utils.train.train_model()
  File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/utils/train.py", line 67, in train_model
    workspace.RunNet(model.net.Proto().name)
  File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.h:433] . Exception encountered running PythonOp function: ValueError: min() arg is an empty sequence

At:
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/utils/segms.py(136): polys_to_boxes
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/roi_data/mask_rcnn.py(46): add_mask_rcnn_blobs
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/roi_data/fast_rcnn.py(197): _sample_rois
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/roi_data/fast_rcnn.py(112): add_fast_rcnn_blobs
  /data/workspace/mingrui/anaconda3/envs/caffe2/lib/python3.5/site-packages/Detectron-0.0.0-py3.5-linux-x86_64.egg/detectron/ops/collect_and_distribute_fpn_rpn_proposals.py(62): forward
Error from operator:
input: "gpu_1/rpn_rois_fpn2" input: "gpu_1/rpn_rois_fpn3" input: "gpu_1/rpn_rois_fpn4" input: "gpu_1/rpn_rois_fpn5" input: "gpu_1/rpn_rois_fpn6" input: "gpu_1/rpn_roi_probs_fpn2" input: "gpu_1/rpn_roi_probs_fpn3" input: "gpu_1/rpn_roi_probs_fpn4" input: "gpu_1/rpn_roi_probs_fpn5" input: "gpu_1/rpn_roi_probs_fpn6" input: "gpu_1/roidb" input: "gpu_1/im_info" output: "gpu_1/rois" output: "gpu_1/labels_int32" output: "gpu_1/bbox_targets" output: "gpu_1/bbox_inside_weights" output: "gpu_1/bbox_outside_weights" output: "gpu_1/mask_rois" output: "gpu_1/roi_has_mask_int32" output: "gpu_1/masks_int32" output: "gpu_1/rois_fpn2" output: "gpu_1/rois_fpn3" output: "gpu_1/rois_fpn4" output: "gpu_1/rois_fpn5" output: "gpu_1/rois_idx_restore_int32" output: "gpu_1/mask_rois_fpn2" output: "gpu_1/mask_rois_fpn3" output: "gpu_1/mask_rois_fpn4" output: "gpu_1/mask_rois_fpn5" output: "gpu_1/mask_rois_idx_restore_int32" name: "CollectAndDistributeFpnRpnProposalsOp:gpu_1/rpn_rois_fpn2,gpu_1/rpn_rois_fpn3,gpu_1/rpn_rois_fpn4,gpu_1/rpn_rois_fpn5,gpu_1/rpn_rois_fpn6,gpu_1/rpn_roi_probs_fpn2,gpu_1/rpn_roi_probs_fpn3,gpu_1/rpn_roi_probs_fpn4,gpu_1/rpn_roi_probs_fpn5,gpu_1/rpn_roi_probs_fpn6,gpu_1/roidb,gpu_1/im_info" type: "Python" arg { name: "token" s: "forward:11" } arg { name: "grad_input_indices" } arg { name: "grad_output_indices" } device_option { device_type: 0 }Error from operator:
input: "gpu_1/rpn_rois_fpn2" input: "gpu_1/rpn_rois_fpn3" input: "gpu_1/rpn_rois_fpn4" input: "gpu_1/rpn_rois_fpn5" input: "gpu_1/rpn_rois_fpn6" input: "gpu_1/rpn_roi_probs_fpn2" input: "gpu_1/rpn_roi_probs_fpn3" input: "gpu_1/rpn_roi_probs_fpn4" input: "gpu_1/rpn_roi_probs_fpn5" input: "gpu_1/rpn_roi_probs_fpn6" input: "gpu_1/roidb" input: "gpu_1/im_info" output: "gpu_1/rois" output: "gpu_1/labels_int32" output: "gpu_1/bbox_targets" output: "gpu_1/bbox_inside_weights" output: "gpu_1/bbox_outside_weights" output: "gpu_1/mask_rois" output: "gpu_1/roi_has_mask_int32" output: "gpu_1/masks_int32" output: "gpu_1/rois_fpn2" output: "gpu_1/rois_fpn3" output: "gpu_1/rois_fpn4" output: "gpu_1/rois_fpn5" output: "gpu_1/rois_idx_restore_int32" output: "gpu_1/mask_rois_fpn2" output: "gpu_1/mask_rois_fpn3" output: "gpu_1/mask_rois_fpn4" output: "gpu_1/mask_rois_fpn5" output: "gpu_1/mask_rois_idx_restore_int32" name: "CollectAndDistributeFpnRpnProposalsOp:gpu_1/rpn_rois_fpn2,gpu_1/rpn_rois_fpn3,gpu_1/rpn_rois_fpn4,gpu_1/rpn_rois_fpn5,gpu_1/rpn_rois_fpn6,gpu_1/rpn_roi_probs_fpn2,gpu_1/rpn_roi_probs_fpn3,gpu_1/rpn_roi_probs_fpn4,gpu_1/rpn_roi_probs_fpn5,gpu_1/rpn_roi_probs_fpn6,gpu_1/roidb,gpu_1/im_info" type: "Python" arg { name: "token" s: "forward:11" } arg { name: "grad_input_indices" } arg { name: "grad_output_indices" } device_option { device_type: 1 device_id: 1 }
```

**Comment by mingruimingrui** [comment]
Appears to be a device mapping error

**Comment by ir413** [comment]
Hi @mingruimingrui, not sure if this was resolved from your follow-up comment? If not, please provide the steps to reproduce the issue together with the system / environment info from the issue template and re-open the issue.
