### ISSUE TITLE
out of memory Error from operator and Negative areas founds

### ISSUE THREAD

**Issue by daoyijushi** [facebookresearch/Detectron#741]
I train faster rcnn based on ResNet-101-FPN and use pre-trained on my dataset. NUM_GPUS=4.

CUDA_VISIBLE_DEVICES=0,1,2,3  python3 -u tools/train_net.py     --cfg configs/getting_started/oid_faster_rcnn_R-101-FPN_2x.yaml   OUTPUT_DIR /tmp/detectron/

Then I encounter the problem: out of memory Error from operator and Negative areas founds.

    Traceback (most recent call last):
  File "tools/train_net.py", line 128, in <module>
    main()
  File "tools/train_net.py", line 110, in main
    checkpoints = detectron.utils.train.train_model()
  File "/mnt/workspace/majian/programs/oid_detectron/detectron/utils/train.py", line 65, in train_model
    workspace.RunNet(model.net.Proto().name)
  File "/mnt/workspace/majian/programs/pytorch/build/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/mnt/workspace/majian/programs/pytorch/build/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.cu:346] error == cudaSuccess. 2 vs 0. Error at: /mnt/workspace/majian/programs/pytorch/caffe2/core/context_gpu.cu:346: out of memoryError from operator:
input: "gpu_0/fpn_inner_res2_2_sum_lateral" input: "gpu_0/fpn_inner_res2_2_sum_topdown" output: "gpu_0/fpn_inner_res2_2_sum" name: "" type: "Sum" device_option { device_type: 1 cuda_gpu_id: 0 }

After I changed Base_LR to 0.0001 and IMS_PER_BATCH to 1, it seems to be OK until now.
But if I only change IMS_PER_BATCH to 1, It still has the  problem of out of memory Error from operator and Negative areas founds. 

I've seen some people have this problem also, but I don't seem to see the cause.
So I  want to know why Base_LR can influence that, could you please tell me the reason about it?

### System information

* Operating system: ubuntu 16.04?
* CUDA version: 8.0.61
* cuDNN version: 7
* NVIDIA driver version: 375.66
* `python --version` output: 3.5

**Comment by ir413** [comment]
Hi @daoyijushi, this should have been addressed by 47e457a. Could you please double-check that your Detectron checkout includes the aforementioned commit?
