### ISSUE TITLE
OSError: libcurand.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#749]
hi! I install caffe2 from canda successfully.  Then I install detectron. when I check that Detectron tests pass:
`python ./detectron/tests/test_spatial_narrow_as_op.py`
I encounter the issue such as:
```
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
Traceback (most recent call last):
  File "./detectron/tests/test_spatial_narrow_as_op.py", line 88, in <module>
    c2_utils.import_detectron_ops()
  File "/home/user/backup/detectron/detectron/utils/c2.py", line 42, in import_detectron_ops
    dyndep.InitOpsLibrary(detectron_ops_lib)
  File "/home/user/anaconda3/envs/python2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/home/user/anaconda3/envs/python2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/home/user/anaconda3/envs/python2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.9.0: cannot open shared object file: No such file or directory
```

**Comment by lilichu** [comment]
well, I used to install old caffe2 from source.
I think it is because that I used to install old caffe2. The old caffe2 libcaffe2.so, libcaffe2_detectron_ops_gpu.so, libcaffe2_gpu.so, libcaffe2_module_test_dynamic.so, libcaffe2_observers.so is in /usr/local/lib, but now new installed caffe2 they all in pytorch/build/lib. I delete all in /usr/local/lib
