### ISSUE TITLE
error saving model after 20000 iterations

### ISSUE THREAD

**Issue by YoungMagic** [facebookresearch/Detectron#75]
Hi~ I tried to train a model following the tutorial GETTING_STARTED.MD. I run the code bellow:
```
python2 tools/train_net.py \
    --cfg configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml \
    OUTPUT_DIR /tmp/detectron-output
```
The training process seems to be ok. But saving the trained model occurs an error, some of the log is below:
```
json_stats: {"accuracy_cls": 0.881836, "eta": "2:13:09", "iter": 19960, "loss": 0.803501, "loss_bbox": 0.207774, "loss_cls": 0.386982, "loss_rpn_bbox_fpn2": 0.010722, "loss_rpn_bbox_fpn3": 0.003304, "loss_rpn_bbox_fpn4": 0.002940, "loss_rpn_bbox_fpn5": 0.014648, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.047052, "loss_rpn_cls_fpn3": 0.015512, "loss_rpn_cls_fpn4": 0.007294, "loss_rpn_cls_fpn5": 0.004592, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 64, "mem": 3300, "time": 0.199536}
json_stats: {"accuracy_cls": 0.878250, "eta": "2:13:05", "iter": 19980, "loss": 0.744052, "loss_bbox": 0.216909, "loss_cls": 0.413512, "loss_rpn_bbox_fpn2": 0.003823, "loss_rpn_bbox_fpn3": 0.001294, "loss_rpn_bbox_fpn4": 0.007347, "loss_rpn_bbox_fpn5": 0.019215, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.026719, "loss_rpn_cls_fpn3": 0.018166, "loss_rpn_cls_fpn4": 0.009227, "loss_rpn_cls_fpn5": 0.002927, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 64, "mem": 3300, "time": 0.199525}
INFO net.py: 135: Saving parameters and momentum to /tmp/detectron-output/train/coco_2014_train/generalized_rcnn/model_iter19999.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 358, in <module>
    main()
  File "tools/train_net.py", line 196, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 228, in train_model
    nu.save_model_to_weights_file(checkpoints[cur_iter], model)
  File "/home/mq/detectron/lib/utils/net.py", line 160, in save_model_to_weights_file
    cfg_yaml = yaml.dump(cfg)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 61, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 447, in represent_object
    return self.represent_mapping(tag+function_name, value)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python2.7/disjson_stats: {"accuracy_cls": 0.881836, "eta": "2:13:09", "iter": 19960, "loss": 0.803501, "loss_bbox": 0.207774, "loss_cls": 0.386982, "loss_rpn_bbox_fpn2": 0.010722, "loss_rpn_bbox_fpn3": 0.003304, "loss_rpn_bbox_fpn4": 0.002940, "loss_rpn_bbox_fpn5": 0.014648, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.047052, "loss_rpn_cls_fpn3": 0.015512, "loss_rpn_cls_fpn4": 0.007294, "loss_rpn_cls_fpn5": 0.004592, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 64, "mem": 3300, "time": 0.199536}
json_stats: {"accuracy_cls": 0.878250, "eta": "2:13:05", "iter": 19980, "loss": 0.744052, "loss_bbox": 0.216909, "loss_cls": 0.413512, "loss_rpn_bbox_fpn2": 0.003823, "loss_rpn_bbox_fpn3": 0.001294, "loss_rpn_bbox_fpn4": 0.007347, "loss_rpn_bbox_fpn5": 0.019215, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.026719, "loss_rpn_cls_fpn3": 0.018166, "loss_rpn_cls_fpn4": 0.009227, "loss_rpn_cls_fpn5": 0.002927, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 64, "mem": 3300, "time": 0.199525}
INFO net.py: 135: Saving parameters and momentum to /tmp/detectron-output/train/coco_2014_train/generalized_rcnn/model_iter19999.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 358, in <module>
    main()
  File "tools/train_net.py", line 196, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 228, in train_model
    nu.save_model_to_weights_file(checkpoints[cur_iter], model)
  File "/home/mq/detectron/lib/utils/net.py", line 160, in save_model_to_weights_file
    cfg_yaml = yaml.dump(cfg)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 61, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 447, in represent_object
    return self.represent_mapping(tag+function_name, value)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 41, in represent_data
    if self.ignore_aliases(data):
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 142, in ignore_aliases
    if data in [None, ()]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()t-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 41, in represent_data
    if self.ignore_aliases(data):
  File "/usr/lib/python2.7/dist-packages/yaml/representer.py", line 142, in ignore_aliases
    if data in [None, ()]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Anyone can help?

**Comment by rbgirshick** [comment]
This looks possibly the same as #23.

**Comment by YoungMagic** [comment]
It works after I update PyYAML to 3.12. Thanks @rbgirshick .
