### ISSUE TITLE
Error when writing graph to image [Errno 2] "dot" not found in path.

### ISSUE THREAD

**Issue by zhangxiang1993** [facebookresearch/Detectron#768]
Hi

I am trying  to convert my .pkl model to .pb. And got this at the end. I got converted model.pb, model.pbtxt and model_init.pb. But I am concern with the Error message. So does it matter?

```
Fusing affine channel...
Writing converted model to /home/xianz/PycharmProjects/caffe2/detectrontest/output...
Saving model graph...
Error when writing graph to image [Errno 2] "dot" not found in path.
Model def image saved to /home/xianz/PycharmProjects/caffe2/detectrontest/output.

Process finished with exit code 0
```
### System information

* Operating system: Ubuntu 16.04
* CUDA version: 9.0
* cuDNN version: 7.1.4
* NVIDIA driver version: NVIDIA-SMI 390.87
* GPU models (for all devices if they are not all the same): GTX 1070
* `python --version` output: 2.7

**Comment by zhangxiang1993** [comment]
My script cannot run smoothly when adding test_img. 
`python
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 6.4218e-05 secs
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 5.0403e-05 secs
[I net_async_base.h:210] Using specified CPU pool size: 4; device id: -1
[I net_async_base.h:215] Created new CPU pool, size: 4; device id: -1
Traceback (most recent call last):
  File "/home/xianz/PycharmProjects/caffe2/detectrontest/convert_pkl_to_pb.py", line 651, in <module>
    main()
  File "/home/xianz/PycharmProjects/caffe2/detectrontest/convert_pkl_to_pb.py", line 645, in main
    verify_model(args, [net, init_net], args.test_img)
  File "/home/xianz/PycharmProjects/caffe2/detectrontest/convert_pkl_to_pb.py", line 583, in verify_model
    _run_cfg_func, _run_pb_func, test_img, check_blobs)
  File "/home/xianz/detectron/detectron/utils/model_convert_utils.py", line 365, in compare_model
    res1 = model1_func(test_image, check_blobs)
  File "/home/xianz/PycharmProjects/caffe2/detectrontest/convert_pkl_to_pb.py", line 576, in _run_cfg_func
    return run_model_cfg(args, im, check_blobs)
  File "/home/xianz/PycharmProjects/caffe2/detectrontest/convert_pkl_to_pb.py", line 465, in run_model_cfg
    boxes, segms, keypoints, classes)
  File "/home/xianz/PycharmProjects/caffe2/detectrontest/convert_pkl_to_pb.py", line 436, in _sort_results
    indices = np.argsort(boxes[:, -1])[::-1]
TypeError: 'NoneType' object has no attribute '__getitem__'
`
