### ISSUE TITLE
Can't find blob: gpu_0/bbox_pred

### ISSUE THREAD

**Issue by GuoxiongZhang** [facebookresearch/Detectron#773]
Hi, all.

I use tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml  in detectron to train my own data set without errors. But the test found that the bbox_pred could not be found.

error log:
[I net_async_base.h:207] Created new CPU pool, size: 4; device id: -1
Traceback (most recent call last):
  File "tools/train_net.py", line 132, in <module>
    main()
  File "tools/train_net.py", line 117, in main
    test_model(checkpoints['final'], args.multi_gpu_testing, args.opts)
  File "tools/train_net.py", line 127, in test_model
    check_expected_results=True,
  File "/home/guoxiong/WorkSpace/detectron/detectron/core/test_engine.py", line 127, in run_inference
    all_results = result_getter()
  File "/home/guoxiong/WorkSpace/detectron/detectron/core/test_engine.py", line 107, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/guoxiong/WorkSpace/detectron/detectron/core/test_engine.py", line 158, in test_net_on_dataset
    weights_file, dataset_name, proposal_file, output_dir, gpu_id=gpu_id
  File "/home/guoxiong/WorkSpace/detectron/detectron/core/test_engine.py", line 257, in test_net
    model, im, box_proposals, timers
  File "/home/guoxiong/WorkSpace/detectron/detectron/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/guoxiong/WorkSpace/detectron/detectron/core/test.py", line 173, in im_detect_bbox
    box_deltas = workspace.FetchBlob(core.ScopedName('bbox_pred')).squeeze()
  File "/usr/local/Anaconda2/envs/pytorchenv/lib/python3.5/site-packages/caffe2/python/workspace.py", line 339, in FetchBlob
    result = C.fetch_blob(StringifyBlobName(name))
RuntimeError: [enforce fail at pybind_state.cc:183] ws->HasBlob(name). Can't find blob: gpu_0/bbox_pred

**Comment by larsoncs** [comment]
me,too
someone can reply  the question?

**Comment by GuoxiongZhang** [comment]
I found this problem because I modified the code in detectron/modeling/fast_rcnn_heads.py, and I changed cls_score to cls_score_voc, bbox_pred to bbox_pred_voc. Change cls_score_voc back to cls_score, bbox_pred_voc back to bbox_pred before running test, the problem disappears.

**Comment by larsoncs** [comment]
I solved it, modify detectron/core/test.py, just using bbox_pred_voc  replace bbox_pred.

**Comment by ir413** [comment]
Closing as the issues seems resolved.
