### ISSUE TITLE
Error in running test_spatial_narrow_as_op.py 

### ISSUE THREAD

**Issue by rabbitegg** [facebookresearch/Detectron#784]
I run detectron on nvidia jetson tx2, after flashing tx2, installing some dependency environment, I install pytorch and detectron, all is good ,until test detectron.
when I run test code, error caused like follow:
`$ python /path/to/clone/detectron/detectron/tests/test_spatial_narrow_as_op.py 
Traceback (most recent call last):
  File "/path/to/clone/detectron/detectron/tests/test_spatial_narrow_as_op.py", line 24, in <module>
    from caffe2.proto import caffe2_pb2
  File "/usr/local/lib/python2.7/dist-packages/caffe2/proto/caffe2_pb2.py", line 23, in <module>
    _CUDA\x10\x01\x12\x10\n\x0cPROTO_MKLDNN\x10\x02\x12\x10\n\x0cPROTO_OPENGL\x10\x03\x12\x10\n\x0cPROTO_OPENCL\x10\x04\x12\x0f\n\x0bPROTO_IDEEP\x10\x05\x12\r\n\tPROTO_HIP\x10\x06\x12\x0e\n\nPROTO_FPGA\x10\x07\x12\'\n#PROTO_COMPILE_TIME_MAX_DEVICE_TYPES\x10\x08\x12\x19\n\x13PROTO_ONLY_FOR_TEST\x10\xa5\xa3\x01')
TypeError: __init__() got an unexpected keyword argument 'syntax'
`

I don't know how to fix it. please help me.

**Comment by rabbitegg** [comment]
did anyone come to help me ? thanks.
