### ISSUE TITLE
Error when change RES5_DILATION to 2

### ISSUE THREAD

**Issue by greathope** [facebookresearch/Detectron#810]
```
Traceback (most recent call last):
  File "tools/train_net.py", line 132, in <module>
    main()
  File "tools/train_net.py", line 114, in main
    checkpoints = detectron.utils.train.train_model()
  File "/data/hope/data/Detectron/detectron/utils/train.py", line 67, in train_model
    workspace.RunNet(model.net.Proto().name)
  File "/home/hope/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 236, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/hope/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 197, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at utility_ops.h:282] . Check failed: output->sizes() == Input(i).sizes().Description: Input #1, input dimension:[1, 256, 128, 168] should match output dimension: [1, 256, 64, 84]
Error from operator: 
input: "gpu_3/fpn_inner_res4_22_sum_lateral" input: "gpu_3/fpn_inner_res4_22_sum_topdown" output: "gpu_3/fpn_inner_res4_22_sum" name: "" type: "Sum" device_option { device_type: 1 device_id: 3 }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x68 (0x7fc1b9e17f68 in /home/hope/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: <unknown function> + 0x26066eb (0x7fc1893576eb in /home/hope/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #2: caffe2::SumOp<caffe2::CUDAContext>::RunOnDevice() + 0x85 (0x7fc189350ea5 in /home/hope/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #3: <unknown function> + 0xf50dc5 (0x7fc187ca1dc5 in /home/hope/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #4: caffe2::AsyncNetBase::run(int, int) + 0x154 (0x7fc199b15d34 in /home/hope/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #5: <unknown function> + 0x13fe655 (0x7fc199b55655 in /home/hope/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #6: c10::ThreadPool::main_loop(unsigned long) + 0x2eb (0x7fc198b8dd9b in /home/hope/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #7: <unknown function> + 0xb8c70 (0x7fc1bf727c70 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x76fa (0x7fc1c6ca16fa in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #9: clone + 0x6d (0x7fc1c62c7b5d in /lib/x86_64-linux-gnu/libc.so.6)
```
can anyone help me?

**Comment by anguoyang** [comment]
can anyone answer this question? @ir413 @rbgirshick
