### ISSUE TITLE
AssertionError: input rpn_rois should be defined in the net. convert_pkl_to_pb.py

### ISSUE THREAD

**Issue by pkuxwguan** [facebookresearch/Detectron#822]
I run convert_pkl_to_pb.py with option '--device gpu' and '--cfg configs/12_2017_baselines/retinanet_X-101-32x8d-FPN_1x.yaml'. I get the following error.
Fusing affine channel...
Traceback (most recent call last):
  File "convert_pkl_to_pb.py", line 653, in <module>
    main()
  File "convert_pkl_to_pb.py", line 641, in main
    [net, init_net] = convert_model_gpu(args, net, init_net)
  File "convert_pkl_to_pb.py", line 377, in convert_model_gpu
    ret = core.InjectDeviceCopiesAmongNets([ret_init_net, ret_net])
  File "/root/anaconda3/lib/python3.7/site-packages/caffe2/python/core.py", line 2518, in InjectDeviceCopiesAmongNets
    blob_remap=blob_remap,
  File "/root/anaconda3/lib/python3.7/site-packages/caffe2/python/core.py", line 2410, in InjectCrossDeviceCopies
    "input {} should be defined in the net.".format(input)
AssertionError: input rpn_rois should be defined in the net.

But I  can convert the 'e2e_faster_rcnn_X-101-32x8d-FPN_1x.yaml' to pb file in gpu model.

**Comment by pranjaljoshi212** [comment]
I got the same error while using "--device gpu".

**Comment by Cyndilee** [comment]
Same error here. Did you find any solution?

**Comment by pkhigh** [comment]
anyone found any solution to this problem. I am also facing the same issue.
