### ISSUE TITLE
evaluation error

### ISSUE THREAD

**Issue by zhuliqian** [facebookresearch/Detectron#828]
INFO test_engine.py: 319: Wrote detections to: /home/chase/detectron/total/test/total_train/generalized_rcnn/detections.pkl
INFO test_engine.py: 161: Total inference time: 172.231s
INFO task_evaluation.py:  76: Evaluating detections
INFO json_dataset_evaluator.py: 181: Writing bbox results json to: /home/chase/detectron/total/test/total_train/generalized_rcnn/bbox_total_train_results.json
Loading and preparing results...
DONE (t=0.17s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=6.73s).
Accumulating evaluation results...
DONE (t=0.26s).
INFO json_dataset_evaluator.py: 241: ~~~~ Mean and per-category AP @ IoU=[0.50,0.95] ~~~~
INFO json_dataset_evaluator.py: 242: 59.8
INFO json_dataset_evaluator.py: 250: 59.8
INFO json_dataset_evaluator.py: 251: ~~~~ Summary metrics ~~~~
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.598
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.926
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.696
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.390
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.596
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.700
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.094
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.534
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.655
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.485
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.656
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.746
INFO json_dataset_evaluator.py: 218: Wrote json eval results to: /home/chase/detectron/total/test/total_train/generalized_rcnn/detection_results.pkl
INFO task_evaluation.py:  62: Evaluating bounding boxes is done!
INFO task_evaluation.py: 105: Evaluating segmentations
INFO json_dataset_evaluator.py:  88: Writing segmentation results json to: /home/chase/detectron/total/test/total_train/generalized_rcnn/segmentations_total_train_results.json
Loading and preparing results...
DONE (t=0.59s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
Traceback (most recent call last):
  File "tools/train_net.py", line 132, in <module>
    main()
  File "tools/train_net.py", line 117, in main
    test_model(checkpoints['final'], args.multi_gpu_testing, args.opts)
  File "tools/train_net.py", line 127, in test_model
    check_expected_results=True,
  File "/home/chase/detectron/detectron/core/test_engine.py", line 127, in run_inference
    all_results = result_getter()
  File "/home/chase/detectron/detectron/core/test_engine.py", line 107, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/chase/detectron/detectron/core/test_engine.py", line 163, in test_net_on_dataset
    dataset, all_boxes, all_segms, all_keyps, output_dir
  File "/home/chase/detectron/detectron/datasets/task_evaluation.py", line 64, in evaluate_all
    results = evaluate_masks(dataset, all_boxes, all_segms, output_dir)
  File "/home/chase/detectron/detectron/datasets/task_evaluation.py", line 114, in evaluate_masks
    cleanup=not_comp
  File "/home/chase/detectron/detectron/datasets/json_dataset_evaluator.py", line 57, in evaluate_masks
    coco_eval = _do_segmentation_eval(json_dataset, res_file, output_dir)
  File "/home/chase/detectron/detectron/datasets/json_dataset_evaluator.py", line 132, in _do_segmentation_eval
    coco_eval.evaluate()
  File "build/bdist.linux-x86_64/egg/pycocotools/cocoeval.py", line 141, in evaluate
  File "build/bdist.linux-x86_64/egg/pycocotools/cocoeval.py", line 105, in _prepare
  File "build/bdist.linux-x86_64/egg/pycocotools/cocoeval.py", line 93, in _toMask
  File "build/bdist.linux-x86_64/egg/pycocotools/coco.py", line 416, in annToRLE
  File "pycocotools/_mask.pyx", line 307, in pycocotools._mask.frPyObjects (pycocotools/_mask.c:7552)
Exception: input type is not supported.

Running correctly on other data sets,
Errors occurred on the data set made by ourselves，
Is there a problem with the data set I made?

**Comment by ir413** [comment]
Hi @zhuliqian, it's hard to tell what the issues is from the provided information. One guess is that your segmentation results may be empty which may cause the COCO eval code to crash. Please reopen the issue with more information (e.g. following the [issue template](https://github.com/facebookresearch/Detectron/blob/master/.github/issue_template.md)).
