### ISSUE TITLE
tools/infer_simple.py fail when input directory contains non-ascii characters

### ISSUE THREAD

**Issue by dmromanov** [facebookresearch/Detectron#874]
### Expected results

No errors in console, successfully parsed images

### Actual results

```
$ python tools/infer_simple.py     --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml     --output-dir /tmp/detectron-visualizations     --image-ext jpg     --wts https://dl.fbaipublicfiles.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl /tmp/пример
....
Traceback (most recent call last):
  File "tools/infer_simple.py", line 185, in <module>
    main(args)
  File "tools/infer_simple.py", line 139, in main
    im_list = glob.iglob(args.im_or_folder + '/*.' + args.image_ext)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 5: ordinal not in range(128)


### Detailed steps to reproduce

1. Create a directory with a name containing non-ascii characters, e.g. cyrillic. `/tmp/пример`
2. Run demo script `infer_simple.py`

```
$ python tools/infer_simple.py     --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml     --output-dir /tmp/detectron-visualizations     --image-ext jpg     --wts https://dl.fbaipublicfiles.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl /tmp/пример
```

### System information

* Operating system: Ubuntu 19.04
* Compiler version: ?
* CUDA version: 10.1
* cuDNN version: 7.5.0.56-1+cuda10.1
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: undefined
* `python --version` output: Python 2.7.16
* Anything else that seems relevant: ?

**Comment by jewelcai** [comment]
Have you solved this issue?

**Comment by dmromanov** [comment]
No, this is still an issue.
