### ISSUE TITLE
What does KeyError: u'area' means ? 

### ISSUE THREAD

**Issue by yoshua133** [facebookresearch/Detectron#890]
Hi, everyone!
When train my custom data using tutorial_2gpu_e2e_faster_rcnn_R-50-FPN, I met this error

INFO memonger.py:  97: Memonger memory optimization took 0.0219588279724 secs
INFO train.py: 192: Loading dataset: ('voc_2007_train',)
loading annotations into memory...
Done (t=0.14s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train_net.py", line 132, in <module>
    main()
  File "tools/train_net.py", line 114, in main
    checkpoints = detectron.utils.train.train_model()
  File "/data2/xiangdawei/detectron/detectron/utils/train.py", line 58, in train_model
    setup_model_for_training(model, weights_file, output_dir)
  File "/data2/xiangdawei/detectron/detectron/utils/train.py", line 170, in setup_model_for_training
    add_model_training_inputs(model)
  File "/data2/xiangdawei/detectron/detectron/utils/train.py", line 194, in add_model_training_inputs
    cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES
  File "/data2/xiangdawei/detectron/detectron/datasets/roidb.py", line 61, in combined_roidb_for_training
    roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
  File "/data2/xiangdawei/detectron/detectron/datasets/roidb.py", line 46, in get_roidb
    crowd_filter_thresh=cfg.TRAIN.CROWD_FILTER_THRESH
  File "/data2/xiangdawei/detectron/detectron/datasets/json_dataset.py", line 109, in get_roidb
    self._add_gt_annotations(entry)
  File "/data2/xiangdawei/detectron/detectron/datasets/json_dataset.py", line 177, in _add_gt_annotations
    if obj['area'] < cfg.TRAIN.GT_MIN_AREA:
KeyError: u'area'

Is this related to json file of the train annotations?

**Comment by r3shma** [comment]
Hello, I am running into the same issue. Did you figure this out?
